packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - esbuild

minimumReleaseAgeExclude:
  - eslint@10.6.0
  - prettier@3.9.0
  - '@tailwindcss/node@4.3.2'
  - '@tailwindcss/oxide-android-arm64@4.3.2'
  - '@tailwindcss/oxide-darwin-arm64@4.3.2'
  - '@tailwindcss/oxide-darwin-x64@4.3.2'
  - '@tailwindcss/oxide-freebsd-x64@4.3.2'
  - '@tailwindcss/oxide-linux-arm-gnueabihf@4.3.2'
  - '@tailwindcss/oxide-linux-arm64-gnu@4.3.2'
  - '@tailwindcss/oxide-linux-arm64-musl@4.3.2'
  - '@tailwindcss/oxide-linux-x64-gnu@4.3.2'
  - '@tailwindcss/oxide-linux-x64-musl@4.3.2'
  - '@tailwindcss/oxide-wasm32-wasi@4.3.2'
  - '@tailwindcss/oxide-win32-arm64-msvc@4.3.2'
  - '@tailwindcss/oxide-win32-x64-msvc@4.3.2'
  - '@tailwindcss/oxide@4.3.2'
  - '@tailwindcss/vite@4.3.2'
  - tailwindcss@4.3.2

catalog:
  '@tanstack/react-query': ^5.101.2
  '@types/react': ^19.2.17
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^6.0.3
  axios: ^1.18.1
  dayjs: ^1.11.21
  happy-dom: ^20.10.6
  i18next: ^26.3.4
  react: ^19.2.7
  react-dom: ^19.2.7
  react-i18next: ^17.0.8
  react-router: ^8.1.0
  typescript: ^6.0.3
  vite: ^8.1.2
  vitest: ^4.1.9
