pub(crate) const RUNTIME_TABLES: &[&str] = &[
    "_sqlx_migrations",
    "system_installation",
    "server_group",
    "plan",
    "payment_method",
    "coupon",
    "users",
    "admin_mfa",
    "orders",
    "commission_log",
    "invite_code",
    "gift_card",
    "gift_card_redemption",
    "payment_reconciliation",
    "knowledge",
    "notice",
    "ticket",
    "ticket_message",
    "system_log",
    "audit_log",
    "mail_log",
    "mail_outbox_batch",
    "mail_outbox",
    "stat",
    "server_traffic",
    "user_traffic",
    "analytics_delivery_batch",
    "analytics_outbox",
    "server_traffic_report",
    "server_traffic_report_item",
    "server_credential",
    "server_route",
    "server_shadowsocks",
    "server_vmess",
    "server_trojan",
    "server_tuic",
    "server_hysteria",
    "server_vless",
    "server_anytls",
    "server_v2node",
    "analytics_admission_policy",
    "analytics_admission_state",
    "operator_config_revision",
    "operator_config_state",
    "operator_config_api_ack",
    "operator_config_worker_ack",
];

pub(crate) const API_SELECT_TABLES: &[&str] = &[
    "_sqlx_migrations",
    "system_installation",
    "server_group",
    "plan",
    "payment_method",
    "coupon",
    "users",
    "admin_mfa",
    "orders",
    "commission_log",
    "invite_code",
    "gift_card",
    "gift_card_redemption",
    "payment_reconciliation",
    "knowledge",
    "notice",
    "ticket",
    "ticket_message",
    "system_log",
    "mail_outbox_batch",
    "stat",
    "server_traffic",
    "user_traffic",
    "analytics_outbox",
    "server_traffic_report",
    "server_credential",
    "server_route",
    "server_shadowsocks",
    "server_vmess",
    "server_trojan",
    "server_tuic",
    "server_hysteria",
    "server_vless",
    "server_anytls",
    "server_v2node",
    "analytics_admission_policy",
    "analytics_admission_state",
    "operator_config_revision",
    "operator_config_state",
];

pub(crate) const API_INSERT_TABLES: &[&str] = &[
    "server_group",
    "plan",
    "payment_method",
    "coupon",
    "users",
    "admin_mfa",
    "orders",
    "invite_code",
    "gift_card",
    "gift_card_redemption",
    "payment_reconciliation",
    "knowledge",
    "notice",
    "ticket",
    "ticket_message",
    "audit_log",
    "mail_outbox_batch",
    "mail_outbox",
    "server_traffic",
    "user_traffic",
    "analytics_outbox",
    "server_traffic_report",
    "server_traffic_report_item",
    "server_credential",
    "server_route",
    "server_shadowsocks",
    "server_vmess",
    "server_trojan",
    "server_tuic",
    "server_hysteria",
    "server_vless",
    "server_anytls",
    "server_v2node",
    "operator_config_revision",
];

pub(crate) const API_UPDATE_TABLES: &[&str] = &[
    "server_group",
    "plan",
    "payment_method",
    "coupon",
    "users",
    "admin_mfa",
    "orders",
    "invite_code",
    "gift_card",
    "payment_reconciliation",
    "knowledge",
    "notice",
    "ticket",
    "mail_outbox_batch",
    "server_traffic",
    "user_traffic",
    "server_credential",
    "server_route",
    "server_shadowsocks",
    "server_vmess",
    "server_trojan",
    "server_tuic",
    "server_hysteria",
    "server_vless",
    "server_anytls",
    "server_v2node",
    "analytics_admission_state",
    "operator_config_state",
];

pub(crate) const API_DELETE_TABLES: &[&str] = &[
    "server_group",
    "plan",
    "coupon",
    "users",
    "admin_mfa",
    "orders",
    "invite_code",
    "gift_card",
    "knowledge",
    "notice",
    "ticket",
    "ticket_message",
    "server_credential",
    "server_route",
    "server_shadowsocks",
    "server_vmess",
    "server_trojan",
    "server_tuic",
    "server_hysteria",
    "server_vless",
    "server_anytls",
    "server_v2node",
];

pub(crate) const WORKER_SELECT_TABLES: &[&str] = &[
    "_sqlx_migrations",
    "system_installation",
    "plan",
    "mail_outbox_batch",
    "mail_outbox",
    "analytics_delivery_batch",
    "analytics_outbox",
    "server_traffic_report",
    "server_traffic_report_item",
    "analytics_admission_policy",
    "analytics_admission_state",
];

pub(crate) const WORKER_INSERT_TABLES: &[&str] = &[
    "mail_outbox_batch",
    "mail_outbox",
    "analytics_delivery_batch",
    "analytics_outbox",
];

pub(crate) const WORKER_UPDATE_TABLES: &[&str] = &[
    "mail_outbox_batch",
    "mail_outbox",
    "analytics_delivery_batch",
    "analytics_outbox",
    "server_traffic_report",
    "analytics_admission_state",
];

pub(crate) const WORKER_DELETE_TABLES: &[&str] = &[
    "system_log",
    "mail_log",
    "mail_outbox_batch",
    "mail_outbox",
    "server_traffic",
    "user_traffic",
    "analytics_delivery_batch",
    "analytics_outbox",
    "server_traffic_report",
    "server_traffic_report_item",
];

#[derive(Clone, Copy)]
pub(crate) struct PostgresColumnGrant {
    pub(crate) privilege: &'static str,
    pub(crate) table: &'static str,
    pub(crate) columns: &'static [&'static str],
}

// Locking SELECTs require UPDATE on at least one column in PostgreSQL. The
// narrow analytics_outbox grant is only that lock capability; API code does not
// update the column.
pub(crate) const API_COLUMN_GRANTS: &[PostgresColumnGrant] = &[
    PostgresColumnGrant {
        privilege: "UPDATE",
        table: "analytics_outbox",
        columns: &["created_at"],
    },
    PostgresColumnGrant {
        privilege: "SELECT",
        table: "operator_config_api_ack",
        columns: &["singleton"],
    },
    PostgresColumnGrant {
        privilege: "INSERT",
        table: "operator_config_api_ack",
        columns: &[
            "singleton",
            "installation_id",
            "observed_revision",
            "applied_revision",
            "status",
            "error_code",
            "observed_at",
        ],
    },
    PostgresColumnGrant {
        privilege: "UPDATE",
        table: "operator_config_api_ack",
        columns: &[
            "observed_revision",
            "applied_revision",
            "status",
            "error_code",
            "observed_at",
        ],
    },
];

// Worker owns queue machinery, but sensitive business and retention tables are
// column-scoped so a compromised scheduler cannot read credentials/messages or
// rewrite identity, ownership, and money fields it never uses.
pub(crate) const WORKER_COLUMN_GRANTS: &[PostgresColumnGrant] = &[
    PostgresColumnGrant {
        privilege: "SELECT",
        table: "payment_method",
        columns: &["id", "payment", "config"],
    },
    PostgresColumnGrant {
        privilege: "SELECT",
        table: "users",
        columns: &[
            "id",
            "invite_user_id",
            "email",
            "balance",
            "discount",
            "commission_type",
            "commission_rate",
            "commission_balance",
            "traffic_epoch",
            "scheduled_traffic_reset_key",
            "u",
            "d",
            "transfer_enable",
            "device_limit",
            "banned",
            "group_id",
            "plan_id",
            "speed_limit",
            "auto_renewal",
            "remind_expire",
            "remind_traffic",
            "expired_at",
            "created_at",
        ],
    },
    PostgresColumnGrant {
        privilege: "UPDATE",
        table: "users",
        columns: &[
            "balance",
            "commission_balance",
            "traffic_epoch",
            "scheduled_traffic_reset_key",
            "t",
            "u",
            "d",
            "transfer_enable",
            "device_limit",
            "group_id",
            "plan_id",
            "speed_limit",
            "auto_renewal",
            "expired_at",
            "updated_at",
        ],
    },
    PostgresColumnGrant {
        privilege: "SELECT",
        table: "orders",
        columns: &[
            "id",
            "invite_user_id",
            "user_id",
            "plan_id",
            "payment_id",
            "type",
            "period",
            "trade_no",
            "callback_no",
            "total_amount",
            "balance_amount",
            "refund_amount",
            "surplus_order_ids",
            "status",
            "commission_status",
            "commission_balance",
            "actual_commission_balance",
            "paid_at",
            "created_at",
            "updated_at",
        ],
    },
    PostgresColumnGrant {
        privilege: "INSERT",
        table: "orders",
        columns: &[
            "user_id",
            "plan_id",
            "type",
            "period",
            "trade_no",
            "total_amount",
            "balance_amount",
            "status",
            "created_at",
            "updated_at",
        ],
    },
    PostgresColumnGrant {
        privilege: "UPDATE",
        table: "orders",
        columns: &[
            "status",
            "commission_status",
            "actual_commission_balance",
            "updated_at",
        ],
    },
    PostgresColumnGrant {
        privilege: "SELECT",
        table: "commission_log",
        columns: &["get_amount", "created_at"],
    },
    PostgresColumnGrant {
        privilege: "INSERT",
        table: "commission_log",
        columns: &[
            "invite_user_id",
            "user_id",
            "trade_no",
            "order_amount",
            "get_amount",
            "created_at",
            "updated_at",
        ],
    },
    PostgresColumnGrant {
        privilege: "SELECT",
        table: "ticket",
        columns: &["id", "user_id", "status", "reply_status", "updated_at"],
    },
    PostgresColumnGrant {
        privilege: "UPDATE",
        table: "ticket",
        columns: &["status", "updated_at"],
    },
    PostgresColumnGrant {
        privilege: "SELECT",
        table: "ticket_message",
        columns: &["id", "ticket_id", "user_id"],
    },
    PostgresColumnGrant {
        privilege: "SELECT",
        table: "system_log",
        columns: &["id", "created_at"],
    },
    PostgresColumnGrant {
        privilege: "SELECT",
        table: "mail_log",
        columns: &["id", "created_at"],
    },
    PostgresColumnGrant {
        privilege: "INSERT",
        table: "mail_log",
        columns: &[
            "email",
            "subject",
            "template_name",
            "error",
            "created_at",
            "updated_at",
        ],
    },
    PostgresColumnGrant {
        privilege: "SELECT",
        table: "stat",
        columns: &["record_at"],
    },
    PostgresColumnGrant {
        privilege: "INSERT",
        table: "stat",
        columns: &[
            "record_at",
            "record_type",
            "order_count",
            "order_total",
            "commission_count",
            "commission_total",
            "paid_count",
            "paid_total",
            "register_count",
            "invite_count",
            "transfer_used_total",
            "created_at",
            "updated_at",
        ],
    },
    PostgresColumnGrant {
        privilege: "UPDATE",
        table: "stat",
        columns: &[
            "order_count",
            "order_total",
            "commission_count",
            "commission_total",
            "paid_count",
            "paid_total",
            "register_count",
            "invite_count",
            "transfer_used_total",
            "updated_at",
        ],
    },
    PostgresColumnGrant {
        privilege: "SELECT",
        table: "server_traffic",
        columns: &["id", "u", "d", "record_at", "created_at"],
    },
    PostgresColumnGrant {
        privilege: "SELECT",
        table: "user_traffic",
        columns: &["id", "record_at"],
    },
    PostgresColumnGrant {
        privilege: "SELECT",
        table: "operator_config_revision",
        columns: &[
            "revision",
            "revision_id",
            "format_version",
            "installation_id",
            "public_config",
            "secret_nonce",
            "secret_ciphertext",
            "secret_tag",
            "config_hmac_sha256",
        ],
    },
    PostgresColumnGrant {
        privilege: "SELECT",
        table: "operator_config_state",
        columns: &["singleton", "installation_id", "active_revision"],
    },
    PostgresColumnGrant {
        privilege: "SELECT",
        table: "operator_config_worker_ack",
        columns: &["singleton"],
    },
    PostgresColumnGrant {
        privilege: "INSERT",
        table: "operator_config_worker_ack",
        columns: &[
            "singleton",
            "installation_id",
            "observed_revision",
            "applied_revision",
            "status",
            "error_code",
            "observed_at",
        ],
    },
    PostgresColumnGrant {
        privilege: "UPDATE",
        table: "operator_config_worker_ack",
        columns: &[
            "observed_revision",
            "applied_revision",
            "status",
            "error_code",
            "observed_at",
        ],
    },
    // PostgreSQL requires one UPDATE-capable column for SELECT ... FOR SHARE;
    // the renewal worker never issues a plan UPDATE.
    PostgresColumnGrant {
        privilege: "UPDATE",
        table: "plan",
        columns: &["updated_at"],
    },
];

pub(crate) const API_SEQUENCES: &[&str] = &[
    "server_group_id_seq",
    "plan_id_seq",
    "payment_method_id_seq",
    "coupon_id_seq",
    "users_id_seq",
    "orders_id_seq",
    "invite_code_id_seq",
    "gift_card_id_seq",
    "payment_reconciliation_id_seq",
    "knowledge_id_seq",
    "notice_id_seq",
    "ticket_id_seq",
    "ticket_message_id_seq",
    "audit_log_id_seq",
    "mail_outbox_id_seq",
    "server_traffic_id_seq",
    "user_traffic_id_seq",
    "analytics_outbox_outbox_id_seq",
    "server_route_id_seq",
    "server_shadowsocks_id_seq",
    "server_vmess_id_seq",
    "server_trojan_id_seq",
    "server_tuic_id_seq",
    "server_hysteria_id_seq",
    "server_vless_id_seq",
    "server_anytls_id_seq",
    "server_v2node_id_seq",
    "operator_config_revision_revision_seq",
];

pub(crate) const WORKER_SEQUENCES: &[&str] = &[
    "orders_id_seq",
    "commission_log_id_seq",
    "mail_log_id_seq",
    "mail_outbox_id_seq",
    "stat_id_seq",
    "analytics_outbox_outbox_id_seq",
];

pub(crate) const RUNTIME_SEQUENCES: &[&str] = &[
    "server_group_id_seq",
    "plan_id_seq",
    "payment_method_id_seq",
    "coupon_id_seq",
    "users_id_seq",
    "orders_id_seq",
    "commission_log_id_seq",
    "invite_code_id_seq",
    "gift_card_id_seq",
    "payment_reconciliation_id_seq",
    "knowledge_id_seq",
    "notice_id_seq",
    "ticket_id_seq",
    "ticket_message_id_seq",
    "system_log_id_seq",
    "audit_log_id_seq",
    "mail_log_id_seq",
    "mail_outbox_id_seq",
    "stat_id_seq",
    "server_traffic_id_seq",
    "user_traffic_id_seq",
    "analytics_outbox_outbox_id_seq",
    "server_route_id_seq",
    "server_shadowsocks_id_seq",
    "server_vmess_id_seq",
    "server_trojan_id_seq",
    "server_tuic_id_seq",
    "server_hysteria_id_seq",
    "server_vless_id_seq",
    "server_anytls_id_seq",
    "server_v2node_id_seq",
    "operator_config_revision_revision_seq",
];
