import type { FormCtx } from '../schema';
import { Section, SwitchRow, TextRow, TextareaRow } from '../rows';
import { isBackendEnabled, parseBackendInteger, parseBackendNumber, splitComma } from '../values';

export function InviteSection({ ctx }: { ctx: FormCtx }) {
  return (
    <Section title="邀请&佣金">
      <SwitchRow
        ctx={ctx}
        group="invite"
        field="invite_force"
        title="开启强制邀请"
        description="开启后只有被邀请的用户才可以进行注册。"
      />
      <TextRow
        ctx={ctx}
        group="invite"
        field="invite_commission"
        title="邀请佣金百分比"
        description="默认全局的佣金分配比例，你可以在用户管理单独配置单个比例。"
        placeholder="请输入"
        coerce={parseBackendInteger}
      />
      <TextRow
        ctx={ctx}
        group="invite"
        field="invite_gen_limit"
        title="用户可创建邀请码上限"
        placeholder="请输入"
        coerce={parseBackendInteger}
      />
      <SwitchRow
        ctx={ctx}
        group="invite"
        field="invite_never_expire"
        title="邀请码永不失效"
        description="开启后邀请码被使用后将不会失效，否则使用过后即失效。"
      />
      <SwitchRow
        ctx={ctx}
        group="invite"
        field="commission_first_time_enable"
        title="佣金仅首次发放"
        description="开启后被邀请人首次支付时才会产生佣金，可以在用户管理对用户进行单独配置。"
      />
      <SwitchRow
        ctx={ctx}
        group="invite"
        field="commission_auto_check_enable"
        title="佣金自动确认"
        description="开启后佣金将会在订单完成3日后自动进行确认。"
      />
      <TextRow
        ctx={ctx}
        group="invite"
        field="commission_withdraw_limit"
        title="提现单申请门槛(元)"
        description="小于门槛金额的提现单将不会被提交。"
        placeholder="请输入"
      />
      <TextareaRow
        ctx={ctx}
        group="invite"
        field="commission_withdraw_method"
        title="提现方式"
        description="可以支持的提现方式。"
        placeholder="请输入后缀域名，逗号分割 如：支付宝,USDT,贝宝"
        rows={4}
        coerce={splitComma}
      />
      <SwitchRow
        ctx={ctx}
        group="invite"
        field="withdraw_close_enable"
        title="关闭提现"
        description="关闭后将禁止用户申请提现，且邀请佣金将会直接进入用户余额。"
      />
      <SwitchRow
        ctx={ctx}
        group="invite"
        field="commission_distribution_enable"
        title="三级分销"
        description="开启后将佣金将按照设置的3成比例进行分成，三成比例合计请不要>100%。"
      />
      {isBackendEnabled(ctx.get('invite', 'commission_distribution_enable')) ? (
        <>
          <TextRow
            ctx={ctx}
            group="invite"
            field="commission_distribution_l1"
            title="一级邀请人比例"
            placeholder="请输入比例如：50"
            indent
            coerce={parseBackendNumber}
          />
          <TextRow
            ctx={ctx}
            group="invite"
            field="commission_distribution_l2"
            title="二级邀请人比例"
            placeholder="请输入比例如：30"
            indent
            coerce={parseBackendNumber}
          />
          <TextRow
            ctx={ctx}
            group="invite"
            field="commission_distribution_l3"
            title="三级邀请人比例"
            placeholder="请输入比例如：20"
            indent
            coerce={parseBackendNumber}
          />
        </>
      ) : null}
    </Section>
  );
}
