import { LEGACY_GB_BYTES } from './env.mjs';

export const guestConfigFixture = {
  app_description: null,
  app_url: null,
  email_whitelist_suffix: ['example.com', 'v2board.test'],
  is_email_verify: 1,
  is_invite_force: 1,
  is_recaptcha: 0,
  logo: null,
  recaptcha_site_key: null,
  tos_url: 'https://example.com/tos',
};
export const userInfoFixture = {
  auto_renewal: 0,
  avatar_url: '',
  balance: 12345,
  banned: 0,
  commission_balance: 10_000_000,
  commission_rate: null,
  created_at: 1_700_000_000,
  device_limit: 5,
  discount: null,
  email: 'visual@example.com',
  expired_at: 4_102_488_000,
  last_login_at: 1_700_000_000,
  plan_id: 1,
  remind_expire: 1,
  remind_traffic: 1,
  telegram_id: null,
  transfer_enable: 1000 * 1024 * 1024 * 1024,
  uuid: 'visual-parity-user',
};
export const bannedUserInfoFixture = {
  ...userInfoFixture,
  banned: 1,
};
export const subscribeFixture = {
  alive_ip: 2,
  allow_new_period: 0,
  d: 200 * 1024 * 1024 * 1024,
  device_limit: 5,
  email: 'visual@example.com',
  expired_at: 4_102_488_000,
  plan: {
    capacity_limit: null,
    content: '',
    created_at: 1_700_000_000,
    device_limit: 5,
    group_id: 1,
    half_year_price: null,
    id: 1,
    month_price: 990,
    name: 'Pro',
    onetime_price: null,
    quarter_price: 2_490,
    renew: 1,
    reset_price: 100,
    reset_traffic_method: 0,
    show: 1,
    sort: 1,
    speed_limit: null,
    three_year_price: null,
    transfer_enable: 1000,
    two_year_price: null,
    updated_at: 1_700_000_000,
    year_price: 9_900,
  },
  plan_id: 1,
  reset_day: 5,
  subscribe_url: 'https://example.test/sub?token=visual',
  token: 'visual-token',
  transfer_enable: 1000 * 1024 * 1024 * 1024,
  u: 650 * 1024 * 1024 * 1024,
  uuid: 'visual-parity-user',
};
export const newPeriodSubscribeFixture = {
  ...subscribeFixture,
  allow_new_period: 1,
  d: 450 * 1024 * 1024 * 1024,
  reset_day: 0,
  u: 550 * 1024 * 1024 * 1024,
};
export const noSubscriptionFixture = {
  ...subscribeFixture,
  alive_ip: 0,
  d: 0,
  device_limit: null,
  expired_at: null,
  plan: null,
  plan_id: null,
  reset_day: null,
  transfer_enable: 0,
  u: 0,
};
export const expiredSubscriptionFixture = {
  ...subscribeFixture,
  expired_at: 1_650_000_000,
  reset_day: null,
};
export const trafficUsedUpSubscribeFixture = {
  ...subscribeFixture,
  allow_new_period: 1,
  d: 0,
  reset_day: 0,
  u: subscribeFixture.transfer_enable,
};
export const deviceLimitReachedSubscribeFixture = {
  ...subscribeFixture,
  alive_ip: 7,
  device_limit: 5,
};
export const expiredTrafficUsedUpSubscribeFixture = {
  ...trafficUsedUpSubscribeFixture,
  expired_at: expiredSubscriptionFixture.expired_at,
  reset_day: null,
};
export const deviceLimitExpiredSubscribeFixture = {
  ...deviceLimitReachedSubscribeFixture,
  expired_at: expiredSubscriptionFixture.expired_at,
  reset_day: null,
};
export const subscribeTargetTitles = [
  'Hiddify',
  'Sing-box',
  'Shadowrocket',
  'QuantumultX',
  'Surge',
  'Stash',
  'ClashX',
  'ClashMeta',
  'NekoBox For Android',
  'ClashMeta For Android',
  'Surfboard',
];
export const planFixtures = [
  {
    capacity_limit: null,
    content: '<p>Fast nodes</p><p>Support ticket</p>',
    count: 12,
    created_at: 1_700_000_000,
    device_limit: 5,
    group_id: 1,
    half_year_price: null,
    id: 1,
    month_price: 990,
    name: 'Pro',
    onetime_price: null,
    quarter_price: 2_490,
    renew: 1,
    reset_price: 100,
    reset_traffic_method: 0,
    show: 1,
    sort: 1,
    speed_limit: null,
    three_year_price: null,
    transfer_enable: 1000,
    two_year_price: null,
    updated_at: 1_700_000_000,
    year_price: 9_900,
  },
  {
    capacity_limit: 3,
    content: '<p>Monthly traffic package</p>',
    count: 2,
    created_at: 1_700_000_000,
    device_limit: null,
    group_id: 1,
    half_year_price: null,
    id: 2,
    month_price: null,
    name: 'Traffic Pack',
    onetime_price: 1_990,
    quarter_price: null,
    renew: 0,
    reset_price: null,
    reset_traffic_method: null,
    show: 1,
    sort: 2,
    speed_limit: null,
    three_year_price: null,
    transfer_enable: 500,
    two_year_price: null,
    updated_at: 1_700_000_000,
    year_price: null,
  },
];
export const orderFixtures = [
  {
    balance_amount: null,
    callback_no: null,
    commission_balance: 0,
    commission_status: 0,
    coupon_id: null,
    created_at: 1_700_000_000,
    discount_amount: null,
    handling_amount: null,
    invite_user_id: null,
    paid_at: null,
    payment_id: null,
    period: 'month_price',
    plan: planFixtures[0],
    plan_id: 1,
    refund_amount: null,
    status: 0,
    surplus_amount: null,
    surplus_order_ids: null,
    total_amount: 990,
    trade_no: 'VISUAL2026110001',
    type: 1,
    updated_at: 1_700_000_000,
  },
  {
    balance_amount: null,
    callback_no: null,
    commission_balance: 0,
    commission_status: 0,
    coupon_id: null,
    created_at: 1_700_086_400,
    discount_amount: null,
    handling_amount: null,
    invite_user_id: null,
    paid_at: 1_700_090_000,
    payment_id: 1,
    period: 'onetime_price',
    plan: planFixtures[1],
    plan_id: 2,
    refund_amount: null,
    status: 3,
    surplus_amount: null,
    surplus_order_ids: null,
    total_amount: 1_990,
    trade_no: 'VISUAL2026110002',
    type: 1,
    updated_at: 1_700_090_000,
  },
];
export const profileDepositTradeNo = 'VISUAL2026110098';
export const profileDepositOrderFixture = {
  balance_amount: null,
  bounus: 0,
  callback_no: null,
  commission_balance: 0,
  commission_status: 0,
  coupon_id: null,
  created_at: 1_700_172_800,
  discount_amount: null,
  get_amount: 1_234,
  handling_amount: null,
  invite_user_id: null,
  paid_at: null,
  payment_id: null,
  period: 'deposit',
  plan: { id: 0, name: 'deposit' },
  plan_id: 0,
  refund_amount: null,
  status: 0,
  surplus_amount: null,
  surplus_order_ids: null,
  total_amount: 1_234,
  trade_no: profileDepositTradeNo,
  type: 9,
  updated_at: 1_700_172_800,
};
export const dashboardResetPackageTradeNo = 'VISUAL2026110097';
export const dashboardResetPackageOrderFixture = {
  balance_amount: null,
  callback_no: null,
  commission_balance: 0,
  commission_status: 0,
  coupon_id: null,
  created_at: 1_700_259_200,
  discount_amount: null,
  handling_amount: null,
  invite_user_id: null,
  paid_at: null,
  payment_id: null,
  period: 'reset_price',
  plan: planFixtures[0],
  plan_id: 1,
  refund_amount: null,
  status: 0,
  surplus_amount: null,
  surplus_order_ids: null,
  total_amount: 100,
  trade_no: dashboardResetPackageTradeNo,
  type: 1,
  updated_at: 1_700_259_200,
};
// /user/order/getPaymentMethod serializes handling_fee_percent as the exact
// NUMERIC decimal string (`handling_fee_percent::text` in db/src/payment.rs).
export const paymentMethodFixtures = [
  {
    handling_fee_fixed: 0,
    handling_fee_percent: '0',
    icon: null,
    id: 1,
    name: 'Alipay',
    payment: 'AlipayF2F',
  },
  {
    handling_fee_fixed: 100,
    handling_fee_percent: '2.5',
    icon: null,
    id: 2,
    name: 'Stripe',
    payment: 'StripeCredit',
  },
  {
    handling_fee_fixed: 100,
    handling_fee_percent: '0',
    icon: null,
    id: 3,
    name: 'Fee Pay',
    payment: 'ManualPay',
  },
];
export const orderPaymentMethodNames = paymentMethodFixtures.map((method) => method.name);
export const couponCheckFixture = {
  code: 'SAVE10',
  created_at: 1_700_000_000,
  ended_at: 4_102_488_000,
  id: 1,
  limit_period: null,
  limit_plan_ids: [1],
  limit_use: null,
  limit_use_with_user: null,
  name: 'Visual Coupon',
  show: 1,
  started_at: 1_600_000_000,
  type: 2,
  updated_at: 1_700_000_000,
  value: 10,
};
export const couponErrorCode = 'BADCODE';
export const checkoutCouponInputSelector =
  '[data-testid="coupon-input"], .v2board-input-coupon, #cashier input[placeholder*="优惠"], #cashier input[placeholder*="Coupon"], #cashier input[placeholder*="coupon"]';
export const checkoutPeriodOptionSelector =
  '#cashier [data-testid="checkout-period-option"], #cashier [data-testid="payment-option"], #cashier .ant-radio-button-wrapper';
export const checkoutCheckedPeriodOptionSelector =
  '#cashier [data-testid="checkout-period-option"][data-state="checked"], #cashier [data-testid="payment-option"][data-state="checked"], #cashier .ant-radio-button-wrapper-checked';
export const knowledgeSearchInputSelector =
  '[data-testid="knowledge-search-bar"] input, .ant-input-search input, input[placeholder*="搜索"], input[placeholder*="Search"]';
export const serverFixtures = [
  {
    cache_key: 'server-1',
    group_id: [1],
    host: 'node-a.example.test',
    id: 1,
    is_online: 1,
    last_check_at: 1_700_000_000,
    name: 'Hong Kong 01',
    parent_id: null,
    port: 443,
    rate: '1',
    route_id: null,
    tags: ['IEPL', 'Netflix'],
    type: 'shadowsocks',
  },
  {
    cache_key: 'server-2',
    group_id: [1],
    host: 'node-b.example.test',
    id: 2,
    is_online: 0,
    last_check_at: 1_700_000_000,
    name: 'Tokyo 02',
    parent_id: null,
    port: 443,
    rate: '2.5',
    route_id: null,
    tags: ['Relay'],
    type: 'trojan',
  },
];
// The legacy oracle wire serializes server_rate as the exact NUMERIC decimal
// string; the source world's modern /user/traffic-logs rows derive JSON
// numbers from these via modernTrafficLogFixture (docs/api-dialect.md §5.4,
// W6).
export const trafficFixtures = [
  {
    d: 1024 * 1024 * 1024,
    record_at: 1_705_320_000,
    server_rate: '1.5',
    u: 512 * 1024 * 1024,
    user_id: 1,
  },
  {
    d: 256 * 1024 * 1024,
    record_at: 1_705_406_400,
    server_rate: '0.5',
    u: 128 * 1024 * 1024,
    user_id: 1,
  },
];
// The admin /stat/getStatUser rows come from jsonb_build_object over the
// NUMERIC column, so server_rate arrives as a JSON number there.
export const adminUserTrafficFixtures = trafficFixtures.map((entry) => ({
  ...entry,
  server_rate: Number(entry.server_rate),
}));
export const inviteFixture = {
  codes: [
    {
      code: 'INVITE2026',
      created_at: 1_700_000_000,
      id: 1,
      pv: 4,
      status: 0,
      updated_at: 1_700_000_000,
      user_id: 1,
    },
    {
      code: 'WELCOME',
      created_at: 1_700_086_400,
      id: 2,
      pv: 2,
      status: 0,
      updated_at: 1_700_086_400,
      user_id: 1,
    },
  ],
  stat: [7, 23_450, 6_780, 12, userInfoFixture.commission_balance],
};
export const inviteDetailFixtures = [
  {
    created_at: 1_700_100_000,
    get_amount: 1_234,
    id: 1,
    invite_user_id: 2,
    order_amount: 9_900,
    order_id: 100,
    trade_no: 'VISUAL-COMMISSION-1',
    updated_at: 1_700_100_000,
    user_id: 1,
  },
  {
    created_at: 1_700_186_400,
    get_amount: 2_345,
    id: 2,
    invite_user_id: 3,
    order_amount: 19_900,
    order_id: 101,
    trade_no: 'VISUAL-COMMISSION-2',
    updated_at: 1_700_186_400,
    user_id: 1,
  },
];
export const ticketFixtures = [
  {
    created_at: 1_700_000_000,
    id: 7,
    level: 1,
    message: [],
    reply_status: 1,
    status: 0,
    subject: 'Need help',
    updated_at: 1_700_000_060,
    user_id: 1,
  },
  {
    created_at: 1_700_086_400,
    id: 8,
    level: 0,
    message: [],
    reply_status: 0,
    status: 0,
    subject: 'Waiting reply',
    updated_at: 1_700_086_460,
    user_id: 1,
  },
  {
    created_at: 1_700_172_800,
    id: 9,
    level: 2,
    message: [],
    reply_status: 0,
    status: 1,
    subject: 'Closed ticket',
    updated_at: 1_700_172_860,
    user_id: 1,
  },
];
export const ticketDetailFixture = {
  ...ticketFixtures[0],
  message: [
    {
      created_at: 1_700_000_120,
      id: 1,
      is_me: false,
      message: 'Hello, how can we help?',
      ticket_id: 7,
      updated_at: 1_700_000_120,
      user_id: 2,
    },
    {
      created_at: 1_700_000_240,
      id: 2,
      is_me: true,
      message: 'I need help with my subscription.',
      ticket_id: 7,
      updated_at: 1_700_000_240,
      user_id: 1,
    },
    {
      created_at: 1_700_000_360,
      id: 3,
      is_me: false,
      message: 'We checked it and the subscription is active now.',
      ticket_id: 7,
      updated_at: 1_700_000_360,
      user_id: 2,
    },
  ],
};
export const knowledgeFixtures = {
  General: [
    {
      body: '<p>Copy article body</p>',
      category: 'General',
      created_at: 1_700_000_000,
      id: 1,
      language: 'en-US',
      show: 1,
      sort: 1,
      title: 'Copy Article',
      updated_at: 1_700_000_000,
    },
  ],
  Router: [
    {
      body: '<p>Router guide body</p>',
      category: 'Router',
      created_at: 1_700_086_400,
      id: 2,
      language: 'en-US',
      show: 1,
      sort: 2,
      title: 'Router Guide',
      updated_at: 1_700_086_400,
    },
  ],
};
export const extremeKnowledgeFixtures = {
  EdgeCases: [
    {
      body:
        '<h2>Extreme Legacy Body</h2>' +
        '<p>extreme-knowledge-token-2026 keeps long inline content, numbers 1234567890, and punctuation aligned.</p>' +
        '<pre>curl --location https://very-long-hostname.edge-parity.example.test/client/subscribe?token=visual</pre>' +
        '<ul><li>Nested legacy list item alpha</li><li>Nested legacy list item beta with a very long phrase that should wrap.</li></ul>',
      category: 'EdgeCases',
      created_at: 1_700_200_000,
      id: 301,
      language: 'en-US',
      show: 1,
      sort: 1,
      title: 'Extreme Legacy Knowledge Matrix Article With Long Title 2026',
      updated_at: 1_700_200_000,
    },
  ],
  Reference: [
    {
      body: '<p>Reference article body for extreme matrix secondary category.</p>',
      category: 'Reference',
      created_at: 1_700_286_400,
      id: 302,
      language: 'en-US',
      show: 1,
      sort: 2,
      title: 'Reference Matrix Article',
      updated_at: 1_700_286_400,
    },
  ],
};
export const adminKnowledgeFixtures = [
  knowledgeFixtures.General[0],
  {
    ...knowledgeFixtures.Router[0],
    show: 0,
  },
];
export const noticeFixtures = [
  {
    content: '<p>Visual parity notice</p>',
    created_at: 1_700_000_000,
    id: 1,
    img_url: null,
    show: 1,
    tags: [],
    title: 'Notice A',
    updated_at: 1_700_000_000,
  },
  {
    content: '<p>Second notice</p>',
    created_at: 1_700_086_400,
    id: 2,
    img_url: null,
    show: 1,
    tags: [],
    title: 'Notice B',
    updated_at: 1_700_086_400,
  },
];
export const adminNoticeFixtures = [
  noticeFixtures[0],
  {
    ...noticeFixtures[1],
    show: 0,
    tags: ['ops'],
    title: 'Hidden Notice',
  },
];
export const userCommConfigFixture = {
  commission_distribution_enable: 0,
  commission_distribution_l1: null,
  commission_distribution_l2: null,
  commission_distribution_l3: null,
  currency: 'CNY',
  currency_symbol: '¥',
  is_telegram: 0,
  telegram_discuss_link: null,
  withdraw_close: 0,
  withdraw_methods: ['Alipay', 'USDT'],
};
export const adminConfigFixture = {
  ticket: {
    ticket_status: 0,
  },
  deposit: {
    deposit_bounus: ['50:18', '100:38'],
  },
  invite: {
    invite_force: 1,
    invite_commission: 10,
    invite_gen_limit: 5,
    invite_never_expire: 0,
    commission_first_time_enable: 1,
    commission_auto_check_enable: 1,
    commission_withdraw_limit: 100,
    commission_withdraw_method: ['支付宝', 'USDT'],
    withdraw_close_enable: 0,
    commission_distribution_enable: 1,
    commission_distribution_l1: 50,
    commission_distribution_l2: 30,
    commission_distribution_l3: 20,
  },
  site: {
    logo: 'https://example.test/logo.png',
    force_https: 1,
    stop_register: 0,
    app_name: 'V2Board',
    app_description: 'V2Board is best!',
    app_url: 'https://example.test',
    subscribe_url: 'https://sub.example.test',
    subscribe_path: '/api/v1/client/subscribe',
    try_out_plan_id: 1,
    try_out_hour: 24,
    tos_url: 'https://example.test/tos',
    currency: 'CNY',
    currency_symbol: '¥',
  },
  subscribe: {
    plan_change_enable: 1,
    reset_traffic_method: 0,
    surplus_enable: 1,
    allow_new_period: 0,
    new_order_event_id: 1,
    renew_order_event_id: 0,
    change_order_event_id: 1,
    show_info_to_server_enable: 1,
    show_subscribe_method: 2,
    show_subscribe_expire: 30,
  },
  frontend: {
    frontend_theme_color: 'default',
    frontend_background_url: null,
    chat_widget_provider: null,
    chat_widget_crisp_website_id: null,
    chat_widget_tawk_property_id: null,
    chat_widget_tawk_widget_id: null,
  },
  server: {
    server_api_url: 'https://node.example.test',
    server_token: 'token',
    server_pull_interval: 60,
    server_push_interval: 60,
    server_node_report_min_traffic: 0,
    server_device_online_min_traffic: 0,
    device_limit_mode: 0,
  },
  email: {
    email_template: 'default',
    email_host: 'smtp.example.test',
    email_port: '465',
    email_username: 'mailer',
    email_password: 'password',
    email_encryption: 'ssl',
    email_from_address: 'noreply@example.test',
  },
  telegram: {
    telegram_bot_enable: 1,
    telegram_bot_token: 'bot-token',
    telegram_discuss_link: 'https://t.me/example',
  },
  app: {
    windows_version: '1.0.0',
    windows_download_url: 'https://example.test/app.exe',
    macos_version: '1.0.0',
    macos_download_url: 'https://example.test/app.dmg',
    android_version: '1.0.0',
    android_download_url: 'https://example.test/app.apk',
  },
  safe: {
    email_verify: 1,
    safe_mode_enable: 1,
    secure_path: 'admin-path',
    email_whitelist_enable: 1,
    email_whitelist_suffix: ['qq.com', 'gmail.com'],
    email_gmail_limit_enable: 1,
    recaptcha_enable: 1,
    recaptcha_key: 'secret',
    recaptcha_site_key: 'site',
    register_limit_by_ip_enable: 1,
    register_limit_count: 3,
    register_limit_expire: 60,
    password_limit_enable: 1,
    password_limit_count: 5,
    password_limit_expire: 60,
  },
};
export const adminEmailTemplateFixtures = ['default', 'classic'];
export const adminStatFixture = {
  commission_last_month_payout: 0,
  commission_month_payout: 0,
  commission_pending_total: 1,
  day_income: 1,
  day_register_total: 0,
  last_month_income: 0,
  month_income: 1,
  month_register_total: 0,
  online_user: 1,
  ticket_pending_total: 1,
};
export const adminQueueStatsFixture = {
  failedJobs: 2,
  jobsPerMinute: 12,
  pausedMasters: 0,
  periods: { failedJobs: 2, recentJobs: 34 },
  processes: 4,
  queueWithMaxRuntime: 'traffic_fetch',
  queueWithMaxThroughput: 'order_handle',
  recentJobs: 34,
  status: true,
  wait: { order_handle: 1, traffic_fetch: 6 },
};
export const adminQueueWorkloadFixtures = [
  { length: 0, name: 'default', processes: 1, wait: 0 },
  { length: 5, name: 'order_handle', processes: 4, wait: 6 },
  { length: 8, name: 'traffic_fetch', processes: 7, wait: 9 },
];
export const adminOrderStatFixtures = [];
export const adminServerRankFixtures = [];
export const adminUserRankFixtures = [];
export const adminPlanStoreFixtures = toAdminPlanStoreFixtures(planFixtures);
export function toAdminPlanStoreFixtures(plans) {
  return plans.map((plan) => {
    const next = { ...plan };
    for (const key of [
      'month_price',
      'quarter_price',
      'half_year_price',
      'year_price',
      'two_year_price',
      'three_year_price',
      'onetime_price',
      'reset_price',
    ]) {
      next[key] = next[key] !== null ? next[key] / 100 : null;
    }
    return next;
  });
}
export const adminServerGroupFixtures = [
  {
    created_at: 1_700_000_000,
    id: 1,
    name: 'Default',
    server_count: 6,
    updated_at: 1_700_000_000,
    user_count: 12,
  },
];
export const adminServerRouteFixtures = [
  {
    action: 'block',
    action_value: null,
    created_at: 1_700_000_000,
    id: 1,
    match: ['geosite:category-ads-all', 'domain:example.com'],
    remarks: 'Block ads',
    updated_at: 1_700_000_000,
  },
  {
    action: 'default_out',
    action_value: JSON.stringify({ protocol: 'freedom' }),
    created_at: 1_700_100_000,
    id: 2,
    match: [],
    remarks: 'Default outbound',
    updated_at: 1_700_100_000,
  },
];
export const adminServerNodeFixtures = [
  {
    available_status: 2,
    group_id: ['1'],
    host: 'jp.example.com',
    id: 1,
    is_online: 1,
    last_check_at: 1_700_000_000,
    name: 'Tokyo 01',
    online: 8,
    parent_id: null,
    port: 443,
    rate: '1.0',
    route_id: [1],
    server_port: 8388,
    show: 1,
    type: 'shadowsocks',
  },
  {
    available_status: 1,
    group_id: ['1'],
    host: 'relay.example.com',
    id: 2,
    is_online: 0,
    last_check_at: null,
    name: 'Tokyo Relay',
    online: 0,
    parent_id: 1,
    port: 8443,
    rate: '0.8',
    route_id: [2],
    server_port: null,
    show: 0,
    type: 'vmess',
  },
];
export const adminOrderFixtures = [
  {
    balance_amount: 0,
    callback_no: null,
    commission_balance: 0,
    commission_status: 0,
    coupon_id: null,
    created_at: 1_700_000_000,
    discount_amount: 0,
    handling_amount: null,
    id: 1,
    invite_user_id: null,
    paid_at: null,
    payment_id: null,
    period: 'month_price',
    plan_id: 1,
    plan_name: 'Pro',
    refund_amount: 0,
    status: 0,
    surplus_amount: 0,
    surplus_order_ids: null,
    total_amount: 990,
    trade_no: 'VISUAL2026110001',
    type: 1,
    updated_at: 1_700_000_000,
    user_id: 1,
  },
  {
    balance_amount: 0,
    callback_no: 'cb-visual-2',
    commission_balance: 120,
    commission_status: 1,
    coupon_id: null,
    created_at: 1_700_086_400,
    discount_amount: 0,
    handling_amount: null,
    id: 2,
    invite_user_id: 3,
    paid_at: 1_700_090_000,
    payment_id: 1,
    period: 'onetime_price',
    plan_id: 2,
    plan_name: 'Traffic Pack',
    refund_amount: 0,
    status: 3,
    surplus_amount: 0,
    surplus_order_ids: null,
    total_amount: 1_990,
    trade_no: 'VISUAL2026110002',
    type: 4,
    updated_at: 1_700_090_000,
    user_id: 2,
  },
];
export const adminUserFixtures = [
  {
    alive_ip: 2,
    balance: 12_340,
    banned: 0,
    commission_balance: 1_230,
    commission_rate: null,
    created_at: 1_700_000_000,
    d: 2_147_483_648,
    device_limit: 3,
    discount: null,
    email: 'visual-user@example.com',
    expired_at: 1_893_456_000,
    group_id: 1,
    id: 1,
    invite_user_id: null,
    ips: '127.0.0.1',
    is_admin: 0,
    is_staff: 0,
    last_login_at: 1_700_000_000,
    password: 'secret',
    plan_id: 1,
    plan_name: 'Pro',
    subscribe_url: 'https://example.com/api/v1/client/subscribe?token=visual-user',
    telegram_id: null,
    token: 'visual-user-token',
    total_used: 3_221_225_472,
    transfer_enable: 107_374_182_400,
    u: 1_073_741_824,
    updated_at: 1_700_000_000,
    uuid: 'visual-user-uuid',
  },
  {
    alive_ip: 0,
    balance: 0,
    banned: 1,
    commission_balance: 0,
    commission_rate: null,
    created_at: 1_700_086_400,
    d: 0,
    device_limit: null,
    discount: null,
    email: 'expired@example.com',
    expired_at: 1_650_000_000,
    group_id: null,
    id: 2,
    invite_user_id: 1,
    ips: '',
    is_admin: 0,
    is_staff: 0,
    last_login_at: null,
    password: 'secret',
    plan_id: null,
    plan_name: null,
    subscribe_url: 'https://example.com/api/v1/client/subscribe?token=expired',
    telegram_id: null,
    token: 'expired-token',
    total_used: 0,
    transfer_enable: 0,
    u: 0,
    updated_at: 1_700_086_400,
    uuid: 'expired-user-uuid',
  },
];
export const adminUserStoreFixtures = toAdminUserStoreFixtures(adminUserFixtures);
export function toAdminUserStoreFixtures(users) {
  return users.map((user) => ({
    ...user,
    balance: legacyScaledFixed(user.balance, 100),
    commission_balance: legacyScaledFixed(user.commission_balance, 100),
    d: legacyScaledFixed(user.d, LEGACY_GB_BYTES),
    password: '',
    total_used: legacyScaledFixed(user.total_used, LEGACY_GB_BYTES),
    transfer_enable: legacyScaledFixed(user.transfer_enable, LEGACY_GB_BYTES),
    u: legacyScaledFixed(user.u, LEGACY_GB_BYTES),
  }));
}
export const adminTicketFixtures = [
  {
    created_at: 1_700_000_000,
    id: 7,
    last_reply_user_id: null,
    level: 2,
    message: [
      {
        created_at: 1_700_000_000,
        id: 1,
        is_me: false,
        message: 'Cannot connect after renewal.',
        ticket_id: 7,
        updated_at: 1_700_000_000,
        user_id: 1,
      },
    ],
    reply_status: 0,
    status: 0,
    subject: 'Connection issue',
    updated_at: 1_700_003_600,
    user_id: 1,
  },
  {
    created_at: 1_700_086_400,
    id: 8,
    last_reply_user_id: 1,
    level: 1,
    message: [
      {
        created_at: 1_700_086_400,
        id: 2,
        is_me: false,
        message: 'Need help changing plan.',
        ticket_id: 8,
        updated_at: 1_700_086_400,
        user_id: 2,
      },
      {
        created_at: 1_700_090_000,
        id: 3,
        is_me: true,
        message: 'Please choose the new plan in orders.',
        ticket_id: 8,
        updated_at: 1_700_090_000,
        user_id: 1,
      },
    ],
    reply_status: 1,
    status: 0,
    subject: 'Plan change',
    updated_at: 1_700_090_000,
    user_id: 2,
  },
];
export const adminTicketDetailFixture = { ...adminTicketFixtures[0] };
export const longDataText =
  'Very Long Legacy Parity Name With Many Segments 2026 Enterprise International Edge Case';
export const longPlanFixtures = Array.from({ length: 6 }, (_, index) => ({
  ...planFixtures[index % planFixtures.length],
  capacity_limit: index % 2 === 0 ? 9999 : null,
  content: `<p>${longDataText} plan body ${index + 1}</p><p>Multiple long benefit lines should wrap like legacy.</p>`,
  count: 900 + index,
  id: 100 + index,
  month_price: 990 + index * 111,
  name: `${longDataText} Plan ${index + 1}`,
  sort: index + 1,
  transfer_enable: 10_000 + index * 1000,
}));
export const longOrderFixtures = Array.from({ length: 12 }, (_, index) => ({
  ...orderFixtures[index % orderFixtures.length],
  created_at: 1_700_000_000 + index * 86_400,
  period: index % 2 === 0 ? 'month_price' : 'year_price',
  plan: longPlanFixtures[index % longPlanFixtures.length],
  plan_id: longPlanFixtures[index % longPlanFixtures.length].id,
  status: index % 4,
  total_amount: 990 + index * 1234,
  trade_no: `VISUALLONG2026${String(index + 1).padStart(4, '0')}`,
  updated_at: 1_700_000_000 + index * 86_400 + 3600,
}));
export const longUserServerFixtures = Array.from({ length: 10 }, (_, index) => ({
  ...serverFixtures[index % serverFixtures.length],
  cache_key: `long-server-${index + 1}`,
  host: `very-long-node-hostname-${index + 1}.international-edge-parity.example.test`,
  id: 100 + index,
  is_online: index % 3 === 0 ? 0 : 1,
  name: `${longDataText} Node ${index + 1}`,
  port: 10_000 + index,
  rate: String(1 + index / 10),
  tags: ['IEPL', 'Netflix', 'Long Region Tag', `Region-${index + 1}`],
  type: index % 2 === 0 ? 'shadowsocks' : 'trojan',
}));
export const longTicketFixtures = Array.from({ length: 10 }, (_, index) => ({
  ...ticketFixtures[index % ticketFixtures.length],
  id: 100 + index,
  level: index % 3,
  reply_status: index % 2,
  status: index % 4 === 0 ? 1 : 0,
  subject: `${longDataText} Ticket Subject ${index + 1}`,
  updated_at: 1_700_000_000 + index * 7200,
}));
export const longTicketDetailFixture = {
  ...ticketDetailFixture,
  subject: `${longDataText} Ticket Detail Subject`,
  message: Array.from({ length: 10 }, (_, index) => ({
    created_at: 1_700_000_000 + index * 600,
    id: 100 + index,
    is_me: index % 2 === 1,
    message: `${longDataText} message bubble ${index + 1}. This message intentionally contains a long sentence to verify legacy wrapping and scroll behavior.`,
    ticket_id: ticketDetailFixture.id,
    updated_at: 1_700_000_000 + index * 600,
    user_id: index % 2 === 1 ? ticketDetailFixture.user_id : 2,
  })),
};
export const longAdminServerNodeFixtures = Array.from({ length: 12 }, (_, index) => ({
  ...adminServerNodeFixtures[index % adminServerNodeFixtures.length],
  available_status: index % 3,
  group_id: ['1'],
  host: `long-admin-node-${index + 1}.operations-control-plane.example.test`,
  id: 100 + index,
  is_online: index % 2,
  name: `${longDataText} Admin Node ${index + 1}`,
  online: 100 + index,
  port: 20_000 + index,
  rate: String(1 + index / 5),
  route_id: [1, 2],
  server_port: 30_000 + index,
  show: index % 2,
  type: ['shadowsocks', 'vmess', 'trojan', 'vless'][index % 4],
}));
export const longAdminOrderFixtures = Array.from({ length: 12 }, (_, index) => ({
  ...adminOrderFixtures[index % adminOrderFixtures.length],
  created_at: 1_700_000_000 + index * 43_200,
  id: 100 + index,
  plan_id: longPlanFixtures[index % longPlanFixtures.length].id,
  plan_name: `${longDataText} Admin Order Plan ${index + 1}`,
  status: index % 4,
  total_amount: 990 + index * 2345,
  trade_no: `ADMINLONG2026${String(index + 1).padStart(4, '0')}`,
  updated_at: 1_700_000_000 + index * 43_200 + 1800,
  user_id: 100 + index,
}));
export const longAdminUserFixtures = Array.from({ length: 12 }, (_, index) => ({
  ...adminUserFixtures[index % adminUserFixtures.length],
  alive_ip: index,
  balance: 999_999 + index,
  banned: index % 5 === 0 ? 1 : 0,
  commission_balance: 123_456 + index,
  d: 1024 * 1024 * 1024 * (index + 1),
  email: `very.long.user.identity.${index + 1}.for.parity.matrix@example-operations.test`,
  expired_at: 1_893_456_000 + index * 86_400,
  group_id: 1,
  id: 100 + index,
  ips: `203.0.113.${index + 1}, 2001:db8::${index + 1}`,
  plan_id: longPlanFixtures[index % longPlanFixtures.length].id,
  plan_name: `${longDataText} User Plan ${index + 1}`,
  subscribe_url: `https://example.com/api/v1/client/subscribe?token=long-user-${index + 1}`,
  token: `long-user-token-${index + 1}`,
  total_used: 1024 * 1024 * 1024 * (index + 5),
  transfer_enable: 1024 * 1024 * 1024 * (index + 50),
  u: 1024 * 1024 * 1024 * (index + 2),
  uuid: `long-user-uuid-${index + 1}`,
}));
export const adminPaymentFixtures = [
  {
    config: {
      mch_id: 'visual-merchant',
      key: 'visual-secret',
    },
    created_at: 1_700_000_000,
    enable: 1,
    handling_fee_fixed: null,
    handling_fee_percent: null,
    icon: null,
    id: 1,
    name: 'Alipay',
    notify_domain: null,
    notify_url: 'https://example.com/api/v1/guest/payment/notify/visual-alipay',
    payment: 'AlipayF2F',
    sort: 1,
    updated_at: 1_700_000_000,
    uuid: 'visual-alipay',
  },
  {
    config: {
      app_id: 'visual-stripe',
      secret_key: 'sk_test_visual',
    },
    created_at: 1_700_086_400,
    enable: 0,
    handling_fee_fixed: 100,
    handling_fee_percent: 2,
    icon: null,
    id: 2,
    name: 'Stripe',
    notify_domain: null,
    notify_url: 'https://example.com/api/v1/guest/payment/notify/visual-stripe',
    payment: 'StripeCheckout',
    sort: 2,
    updated_at: 1_700_086_400,
    uuid: 'visual-stripe',
  },
];
export const adminPaymentMethodsFixture = ['AlipayF2F', 'StripeCheckout', 'MGate'];
export const adminPaymentFormFixtures = {
  AlipayF2F: {
    key: {
      description: '请输入支付宝当面付密钥',
      label: '密钥',
      type: 'input',
      value: 'visual-secret-default',
    },
    mch_id: {
      description: '请输入支付宝商户ID',
      label: '商户ID',
      type: 'input',
      value: 'visual-merchant-default',
    },
  },
  MGate: {
    token: {
      description: '请输入 MGate Token',
      label: 'Token',
      type: 'input',
      value: 'visual-mgate-token',
    },
  },
  StripeCheckout: {
    publishable_key: {
      description: '请输入 Stripe Publishable Key',
      label: 'Publishable Key',
      type: 'input',
      value: 'pk_test_visual',
    },
    secret_key: {
      description: '请输入 Stripe Secret Key',
      label: 'Secret Key',
      type: 'input',
      value: 'sk_test_visual_default',
    },
  },
};
export const adminCouponFixtures = [
  {
    code: 'VISUAL100',
    created_at: 1_700_000_000,
    ended_at: 1_893_456_000,
    id: 1,
    limit_period: ['month_price', 'year_price'],
    limit_plan_ids: [1],
    limit_use: 50,
    limit_use_with_user: 1,
    name: 'Visual Amount',
    show: 1,
    started_at: 1_700_000_000,
    type: 1,
    updated_at: 1_700_000_000,
    value: 1_000,
  },
  {
    code: 'VISUAL20',
    created_at: 1_700_086_400,
    ended_at: 1_893_456_000,
    id: 2,
    limit_period: null,
    limit_plan_ids: null,
    limit_use: null,
    limit_use_with_user: null,
    name: 'Visual Percent',
    show: 0,
    started_at: 1_700_086_400,
    type: 2,
    updated_at: 1_700_086_400,
    value: 20,
  },
];
export const adminCouponStoreFixtures = adminCouponFixtures.map((coupon) => ({
  ...coupon,
  value: coupon.type === 1 ? coupon.value / 100 : coupon.value,
}));
export const adminGiftcardFixtures = [
  {
    code: 'GC-VISUAL-1000',
    created_at: 1_700_000_000,
    ended_at: 1_893_456_000,
    id: 1,
    limit_use: 3,
    name: 'Balance Gift',
    plan_id: null,
    started_at: 1_700_000_000,
    type: 1,
    updated_at: 1_700_000_000,
    used_user_ids: null,
    value: 1_000,
  },
  {
    code: 'GC-VISUAL-PLAN',
    created_at: 1_700_086_400,
    ended_at: 1_893_456_000,
    id: 2,
    limit_use: null,
    name: 'Plan Gift',
    plan_id: 1,
    started_at: 1_700_086_400,
    type: 5,
    updated_at: 1_700_086_400,
    used_user_ids: null,
    value: 30,
  },
];
export const adminGiftcardStoreFixtures = adminGiftcardFixtures.map((giftcard) => ({
  ...giftcard,
  value: giftcard.type === 1 ? giftcard.value / 100 : giftcard.value,
}));

export function legacyScaledFixed(value, divisor) {
  return (Number(value) / divisor).toFixed(2);
}
