import {
  userAuthSurfaceSelector,
  dashboardShortcutSelector,
  dashboardEmptyPlanReadySelector,
  dashboardExpiredReadySelector,
  dashboardTrafficUsedUpReadySelector,
  dashboardProgressReadySelector,
  orderDetailReadySelector,
  userNodeRowsReadySelector,
  userNodeEmptyReadySelector,
  userNodeLoadingReadySelector,
  userTrafficRowsReadySelector,
  userTrafficSurfaceReadySelector,
} from './selectors.mjs';

// Scenario `path`/`warmupPath` values are canonical SPA route paths
// (docs/api-dialect.md §13.4a). world.mjs maps them to per-world entry URLs
// through the page-location canonicalizer: `/#/x?y` for the hash-routed
// oracle, `/x?y` for the history-routed source world, with admin scenarios
// (label prefix `admin-`) mounted under `/{admin_path}`. A scenario with
// `legacyHashEntry: true` instead enters the source world through the legacy
// `/#/x` URL to pin the §10.3 boot translator (toggle default-ON).
const scenarios = [
  // `/` redirects an unauthenticated visit to the redesigned /login surface, so user-home-root*
  // screenshots the reskinned login: its pixel diff against the old oracle is retired alongside
  // user-login*. The behavior gate still holds via the user-home-root-page-state interaction.
  {
    label: 'user-home-root',
    path: '/',
    readySelector: userAuthSurfaceSelector,
    visualRetired: true,
  },
  { label: 'user-login', path: '/login', visualRetired: true },
  { label: 'user-register-rich', path: '/register?code=INVITE2026', visualRetired: true },
  // §W1: enter the path-routed source world through the legacy hash URL to pin
  // the §10.3 boot translator (query preserved, hash consumed).
  {
    label: 'user-register-legacy-hash-entry',
    legacyHashEntry: true,
    path: '/register?code=INVITE2026',
    visualRetired: true,
  },
  { label: 'user-forget', path: '/forgetpassword', visualRetired: true },
  {
    authenticated: true,
    label: 'user-dashboard',
    path: '/dashboard',
    readySelector: dashboardShortcutSelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    forceUserUnauthorized: true,
    label: 'user-dashboard-session-expired',
    path: '/dashboard',
    postReadyDelay: 300,
    readySelector: userAuthSurfaceSelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-dashboard-no-subscription',
    noSubscription: true,
    path: '/dashboard',
    readySelector: dashboardEmptyPlanReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    expiredSubscription: true,
    label: 'user-dashboard-expired-subscription',
    path: '/dashboard',
    readySelector: dashboardExpiredReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-dashboard-traffic-used-up',
    path: '/dashboard',
    readySelector: dashboardTrafficUsedUpReadySelector,
    trafficUsedUp: true,
    visualRetired: true,
  },
  {
    authenticated: true,
    deviceLimitReached: true,
    label: 'user-dashboard-device-limit-reached',
    path: '/dashboard',
    readySelector: dashboardProgressReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    bannedUser: true,
    label: 'user-dashboard-banned',
    path: '/dashboard',
    readySelector: dashboardShortcutSelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    bannedUser: true,
    label: 'user-dashboard-banned-no-subscription',
    noSubscription: true,
    path: '/dashboard',
    readySelector: dashboardEmptyPlanReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    expiredTrafficUsedUp: true,
    label: 'user-dashboard-expired-traffic-used-up',
    path: '/dashboard',
    readySelector: dashboardExpiredReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    deviceLimitExpired: true,
    label: 'user-dashboard-device-limit-expired',
    path: '/dashboard',
    readySelector: dashboardProgressReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    darkMode: true,
    label: 'user-dashboard-dark',
    path: '/dashboard',
    readySelector: dashboardShortcutSelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plans',
    path: '/plan',
    readySelector: '[data-testid="plan-card"], .block-link-pop',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plans-long-data',
    longData: true,
    path: '/plan',
    postReadyDelay: 300,
    readySelector: '[data-testid="plan-card"], .block-link-pop',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plans-sold-out',
    path: '/plan',
    readySelector:
      '[data-testid="plan-card"][aria-disabled="true"], .block-link-pop button[disabled]',
    soldOutPlans: true,
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyPlans: true,
    label: 'user-plans-empty',
    path: '/plan',
    readySelector: '[data-testid="plan-empty"], .spinner-grow',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plans-timeout',
    path: '/plan',
    postReadyDelay: 800,
    readySelector: '#page-container',
    userPlansTimeout: true,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plan-checkout',
    path: '/plan/1',
    readySelector: '#cashier',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plan-checkout-non-renewable',
    nonRenewablePlan: true,
    path: '/plan/1',
    readySelector: '[data-testid="plan-non-renewable"], .ant-result-info',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-orders',
    path: '/order',
    readySelector: '[data-testid="orders-table"] tbody tr, .ant-table-tbody tr',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-orders-long-data',
    longData: true,
    path: '/order',
    postReadyDelay: 300,
    readySelector: '[data-testid="orders-table"] tbody tr, .ant-table-tbody tr',
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyOrders: true,
    label: 'user-orders-empty',
    path: '/order',
    readySelector: '[data-testid="orders-empty"], .ant-table-placeholder .ant-empty',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-orders-api-500',
    path: '/order',
    postReadyDelay: 500,
    readySelector: '[data-testid="orders-card"], .ant-table',
    userOrdersHttpError: true,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-orders-timeout',
    path: '/order',
    postReadyDelay: 800,
    readySelector: '[data-testid="orders-card"], .ant-table',
    userOrdersTimeout: true,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-order-detail',
    path: '/order/VISUAL2026110001',
    readySelector: orderDetailReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-node',
    path: '/node',
    readySelector: userNodeRowsReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-node-long-data',
    longData: true,
    path: '/node',
    postReadyDelay: 300,
    readySelector: userNodeRowsReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyServers: true,
    label: 'user-node-empty',
    path: '/node',
    readySelector: userNodeEmptyReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-node-api-500',
    path: '/node',
    postReadyDelay: 500,
    readySelector: userNodeEmptyReadySelector,
    userServersHttpError: true,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-node-timeout',
    path: '/node',
    postReadyDelay: 800,
    readySelector: userNodeLoadingReadySelector,
    userServersTimeout: true,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-traffic',
    path: '/traffic',
    readySelector: userTrafficRowsReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-traffic-timeout',
    path: '/traffic',
    postReadyDelay: 800,
    readySelector: userTrafficSurfaceReadySelector,
    userTrafficTimeout: true,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-invite',
    path: '/invite',
    readySelector: '[data-testid="invite-surface"], .ant-pagination',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-tickets',
    path: '/ticket',
    readySelector: '[data-testid="ticket-table"], .ant-table-fixed-right',
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyTickets: true,
    label: 'user-tickets-empty',
    path: '/ticket',
    readySelector: '[data-testid="ticket-empty"]',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-tickets-timeout',
    path: '/ticket',
    postReadyDelay: 800,
    readySelector: '[data-testid="ticket-surface"], .ant-table',
    userTicketsTimeout: true,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-ticket-detail',
    path: '/ticket/7',
    readySelector: '[data-testid="ticket-reply-input"], .js-chat-input',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-ticket-detail-long-thread',
    longData: true,
    path: '/ticket/7',
    postReadyDelay: 300,
    readySelector: '[data-testid="ticket-reply-input"], .js-chat-input',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-knowledge',
    path: '/knowledge',
    readySelector: '[data-testid="knowledge-item"], .list-group-item',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-knowledge-timeout',
    path: '/knowledge',
    postReadyDelay: 800,
    readySelector: '[data-testid="knowledge-surface"], #page-container',
    userKnowledgeTimeout: true,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-profile',
    path: '/profile',
    readySelector: '[data-testid="profile-page"], .ant-switch',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-dashboard-no-subscription-zh-tw',
    locale: 'zh-TW',
    noSubscription: true,
    path: '/dashboard',
    readySelector: dashboardEmptyPlanReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    expiredSubscription: true,
    label: 'user-dashboard-expired-subscription-zh-tw',
    locale: 'zh-TW',
    path: '/dashboard',
    readySelector: dashboardExpiredReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-dashboard-traffic-used-up-zh-tw',
    locale: 'zh-TW',
    path: '/dashboard',
    readySelector: dashboardTrafficUsedUpReadySelector,
    trafficUsedUp: true,
    visualRetired: true,
  },
  {
    authenticated: true,
    deviceLimitReached: true,
    label: 'user-dashboard-device-limit-reached-zh-tw',
    locale: 'zh-TW',
    path: '/dashboard',
    readySelector: dashboardProgressReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    bannedUser: true,
    label: 'user-dashboard-banned-zh-tw',
    locale: 'zh-TW',
    path: '/dashboard',
    readySelector: dashboardShortcutSelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    darkMode: true,
    label: 'user-dashboard-dark-zh-tw',
    locale: 'zh-TW',
    path: '/dashboard',
    readySelector: dashboardShortcutSelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plans-long-data-zh-tw',
    locale: 'zh-TW',
    longData: true,
    path: '/plan',
    postReadyDelay: 300,
    readySelector: '[data-testid="plan-card"], .block-link-pop',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plans-sold-out-zh-tw',
    locale: 'zh-TW',
    path: '/plan',
    readySelector:
      '[data-testid="plan-card"][aria-disabled="true"], .block-link-pop button[disabled]',
    soldOutPlans: true,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plan-checkout-non-renewable-zh-tw',
    locale: 'zh-TW',
    nonRenewablePlan: true,
    path: '/plan/1',
    readySelector: '[data-testid="plan-non-renewable"], .ant-result-info',
    visualRetired: true,
  },
  {
    authenticated: true,
    forceUserUnauthorized: true,
    label: 'user-dashboard-session-expired-zh-tw',
    locale: 'zh-TW',
    path: '/dashboard',
    postReadyDelay: 300,
    readySelector: '[data-testid="admin-login-surface"], .v2board-auth-box',
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyPlans: true,
    label: 'user-plans-empty-zh-tw',
    locale: 'zh-TW',
    path: '/plan',
    readySelector: '[data-testid="plan-empty"], .spinner-grow',
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyOrders: true,
    label: 'user-orders-empty-zh-tw',
    locale: 'zh-TW',
    path: '/order',
    readySelector: '[data-testid="orders-empty"], .ant-table-placeholder .ant-empty',
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyServers: true,
    label: 'user-node-empty-zh-tw',
    locale: 'zh-TW',
    path: '/node',
    readySelector: userNodeEmptyReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyTickets: true,
    label: 'user-tickets-empty-zh-tw',
    locale: 'zh-TW',
    path: '/ticket',
    readySelector: '[data-testid="ticket-empty"]',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-orders-long-data-zh-tw',
    locale: 'zh-TW',
    longData: true,
    path: '/order',
    postReadyDelay: 300,
    readySelector: '[data-testid="orders-table"] tbody tr, .ant-table-tbody tr',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-node-long-data-zh-tw',
    locale: 'zh-TW',
    longData: true,
    path: '/node',
    postReadyDelay: 300,
    readySelector: userNodeRowsReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-dashboard-no-subscription-en-us',
    locale: 'en-US',
    noSubscription: true,
    path: '/dashboard',
    readySelector: dashboardEmptyPlanReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    expiredSubscription: true,
    label: 'user-dashboard-expired-subscription-en-us',
    locale: 'en-US',
    path: '/dashboard',
    readySelector: dashboardExpiredReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-dashboard-traffic-used-up-en-us',
    locale: 'en-US',
    path: '/dashboard',
    readySelector: dashboardTrafficUsedUpReadySelector,
    trafficUsedUp: true,
    visualRetired: true,
  },
  {
    authenticated: true,
    deviceLimitReached: true,
    label: 'user-dashboard-device-limit-reached-en-us',
    locale: 'en-US',
    path: '/dashboard',
    readySelector: dashboardProgressReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    bannedUser: true,
    label: 'user-dashboard-banned-en-us',
    locale: 'en-US',
    path: '/dashboard',
    readySelector: dashboardShortcutSelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    darkMode: true,
    label: 'user-dashboard-dark-en-us',
    locale: 'en-US',
    path: '/dashboard',
    readySelector: dashboardShortcutSelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plans-long-data-en-us',
    locale: 'en-US',
    longData: true,
    path: '/plan',
    postReadyDelay: 300,
    readySelector: '[data-testid="plan-card"], .block-link-pop',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plans-sold-out-en-us',
    locale: 'en-US',
    path: '/plan',
    readySelector:
      '[data-testid="plan-card"][aria-disabled="true"], .block-link-pop button[disabled]',
    soldOutPlans: true,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plan-checkout-non-renewable-en-us',
    locale: 'en-US',
    nonRenewablePlan: true,
    path: '/plan/1',
    readySelector: '[data-testid="plan-non-renewable"], .ant-result-info',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-orders-long-data-en-us',
    locale: 'en-US',
    longData: true,
    path: '/order',
    postReadyDelay: 300,
    readySelector: '[data-testid="orders-table"] tbody tr, .ant-table-tbody tr',
    visualRetired: true,
  },
  {
    authenticated: true,
    forceUserUnauthorized: true,
    label: 'user-dashboard-session-expired-en-us',
    locale: 'en-US',
    path: '/dashboard',
    postReadyDelay: 300,
    readySelector: '[data-testid="admin-login-surface"], .v2board-auth-box',
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyPlans: true,
    label: 'user-plans-empty-en-us',
    locale: 'en-US',
    path: '/plan',
    readySelector: '[data-testid="plan-empty"], .spinner-grow',
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyOrders: true,
    label: 'user-orders-empty-en-us',
    locale: 'en-US',
    path: '/order',
    readySelector: '[data-testid="orders-empty"], .ant-table-placeholder .ant-empty',
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyServers: true,
    label: 'user-node-empty-en-us',
    locale: 'en-US',
    path: '/node',
    readySelector: userNodeEmptyReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyTickets: true,
    label: 'user-tickets-empty-en-us',
    locale: 'en-US',
    path: '/ticket',
    readySelector: '[data-testid="ticket-empty"]',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-node-long-data-en-us',
    locale: 'en-US',
    longData: true,
    path: '/node',
    postReadyDelay: 300,
    readySelector: userNodeRowsReadySelector,
    visualRetired: true,
  },
  {
    label: 'user-home-root-zh-tw',
    locale: 'zh-TW',
    path: '/',
    readySelector: '[data-testid="admin-login-surface"], .v2board-auth-box',
    visualRetired: true,
  },
  { label: 'user-login-zh-tw', locale: 'zh-TW', path: '/login', visualRetired: true },
  {
    label: 'user-register-rich-zh-tw',
    locale: 'zh-TW',
    path: '/register?code=INVITE2026',
    visualRetired: true,
  },
  { label: 'user-forget-zh-tw', locale: 'zh-TW', path: '/forgetpassword', visualRetired: true },
  {
    authenticated: true,
    label: 'user-dashboard-zh-tw',
    locale: 'zh-TW',
    path: '/dashboard',
    readySelector: dashboardShortcutSelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plans-zh-tw',
    locale: 'zh-TW',
    path: '/plan',
    readySelector: '[data-testid="plan-card"], .block-link-pop',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plan-checkout-zh-tw',
    locale: 'zh-TW',
    path: '/plan/1',
    readySelector: '#cashier',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-orders-zh-tw',
    locale: 'zh-TW',
    path: '/order',
    readySelector: '[data-testid="orders-table"] tbody tr, .ant-table-tbody tr',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-order-detail-zh-tw',
    locale: 'zh-TW',
    path: '/order/VISUAL2026110001',
    readySelector: orderDetailReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-node-zh-tw',
    locale: 'zh-TW',
    path: '/node',
    readySelector: userNodeRowsReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-traffic-zh-tw',
    locale: 'zh-TW',
    path: '/traffic',
    readySelector: userTrafficRowsReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-invite-zh-tw',
    locale: 'zh-TW',
    path: '/invite',
    readySelector: '[data-testid="invite-surface"], .ant-pagination',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-tickets-zh-tw',
    locale: 'zh-TW',
    path: '/ticket',
    readySelector: '[data-testid="ticket-table"]',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-ticket-detail-zh-tw',
    locale: 'zh-TW',
    path: '/ticket/7',
    readySelector: '[data-testid="ticket-reply-input"], .js-chat-input',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-knowledge-zh-tw',
    locale: 'zh-TW',
    path: '/knowledge',
    readySelector: '[data-testid="knowledge-item"], .list-group-item',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-profile-zh-tw',
    locale: 'zh-TW',
    path: '/profile',
    readySelector: '[data-testid="profile-page"], .ant-switch',
    visualRetired: true,
  },
  {
    label: 'user-home-root-en-us',
    locale: 'en-US',
    path: '/',
    readySelector: '[data-testid="admin-login-surface"], .v2board-auth-box',
    visualRetired: true,
  },
  { label: 'user-login-en-us', locale: 'en-US', path: '/login', visualRetired: true },
  {
    label: 'user-register-rich-en-us',
    locale: 'en-US',
    path: '/register?code=INVITE2026',
    visualRetired: true,
  },
  { label: 'user-forget-en-us', locale: 'en-US', path: '/forgetpassword', visualRetired: true },
  {
    authenticated: true,
    label: 'user-dashboard-en-us',
    locale: 'en-US',
    path: '/dashboard',
    readySelector: dashboardShortcutSelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plans-en-us',
    locale: 'en-US',
    path: '/plan',
    readySelector: '[data-testid="plan-card"], .block-link-pop',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plan-checkout-en-us',
    locale: 'en-US',
    path: '/plan/1',
    readySelector: '#cashier',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-orders-en-us',
    locale: 'en-US',
    path: '/order',
    readySelector: '[data-testid="orders-table"] tbody tr, .ant-table-tbody tr',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-order-detail-en-us',
    locale: 'en-US',
    path: '/order/VISUAL2026110001',
    readySelector: orderDetailReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-node-en-us',
    locale: 'en-US',
    path: '/node',
    readySelector: userNodeRowsReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-traffic-en-us',
    locale: 'en-US',
    path: '/traffic',
    readySelector: userTrafficRowsReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-invite-en-us',
    locale: 'en-US',
    path: '/invite',
    readySelector: '[data-testid="invite-surface"], .ant-pagination',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-tickets-en-us',
    locale: 'en-US',
    path: '/ticket',
    readySelector: '[data-testid="ticket-table"]',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-ticket-detail-en-us',
    locale: 'en-US',
    path: '/ticket/7',
    readySelector: '[data-testid="ticket-reply-input"], .js-chat-input',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-knowledge-en-us',
    locale: 'en-US',
    path: '/knowledge',
    readySelector: '[data-testid="knowledge-item"], .list-group-item',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-profile-en-us',
    locale: 'en-US',
    path: '/profile',
    readySelector: '[data-testid="profile-page"], .ant-switch',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-dashboard-no-subscription-ja-jp',
    locale: 'ja-JP',
    noSubscription: true,
    path: '/dashboard',
    readySelector: dashboardEmptyPlanReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    expiredSubscription: true,
    label: 'user-dashboard-expired-subscription-ja-jp',
    locale: 'ja-JP',
    path: '/dashboard',
    readySelector: dashboardExpiredReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-dashboard-traffic-used-up-ja-jp',
    locale: 'ja-JP',
    path: '/dashboard',
    readySelector: dashboardTrafficUsedUpReadySelector,
    trafficUsedUp: true,
    visualRetired: true,
  },
  {
    authenticated: true,
    deviceLimitReached: true,
    label: 'user-dashboard-device-limit-reached-ja-jp',
    locale: 'ja-JP',
    path: '/dashboard',
    readySelector: dashboardProgressReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    bannedUser: true,
    label: 'user-dashboard-banned-ja-jp',
    locale: 'ja-JP',
    path: '/dashboard',
    readySelector: dashboardShortcutSelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    darkMode: true,
    label: 'user-dashboard-dark-ja-jp',
    locale: 'ja-JP',
    path: '/dashboard',
    readySelector: dashboardShortcutSelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plans-long-data-ja-jp',
    locale: 'ja-JP',
    longData: true,
    path: '/plan',
    postReadyDelay: 300,
    readySelector: '[data-testid="plan-card"], .block-link-pop',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plans-sold-out-ja-jp',
    locale: 'ja-JP',
    path: '/plan',
    readySelector:
      '[data-testid="plan-card"][aria-disabled="true"], .block-link-pop button[disabled]',
    soldOutPlans: true,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plan-checkout-non-renewable-ja-jp',
    locale: 'ja-JP',
    nonRenewablePlan: true,
    path: '/plan/1',
    readySelector: '[data-testid="plan-non-renewable"], .ant-result-info',
    visualRetired: true,
  },
  {
    authenticated: true,
    forceUserUnauthorized: true,
    label: 'user-dashboard-session-expired-ja-jp',
    locale: 'ja-JP',
    path: '/dashboard',
    postReadyDelay: 300,
    readySelector: '[data-testid="admin-login-surface"], .v2board-auth-box',
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyPlans: true,
    label: 'user-plans-empty-ja-jp',
    locale: 'ja-JP',
    path: '/plan',
    readySelector: '[data-testid="plan-empty"], .spinner-grow',
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyOrders: true,
    label: 'user-orders-empty-ja-jp',
    locale: 'ja-JP',
    path: '/order',
    readySelector: '[data-testid="orders-empty"], .ant-table-placeholder .ant-empty',
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyServers: true,
    label: 'user-node-empty-ja-jp',
    locale: 'ja-JP',
    path: '/node',
    readySelector: userNodeEmptyReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyTickets: true,
    label: 'user-tickets-empty-ja-jp',
    locale: 'ja-JP',
    path: '/ticket',
    readySelector: '[data-testid="ticket-empty"]',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-orders-long-data-ja-jp',
    locale: 'ja-JP',
    longData: true,
    path: '/order',
    postReadyDelay: 300,
    readySelector: '[data-testid="orders-table"] tbody tr, .ant-table-tbody tr',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-node-long-data-ja-jp',
    locale: 'ja-JP',
    longData: true,
    path: '/node',
    postReadyDelay: 300,
    readySelector: userNodeRowsReadySelector,
    visualRetired: true,
  },
  {
    label: 'user-home-root-ja-jp',
    locale: 'ja-JP',
    path: '/',
    readySelector: '[data-testid="admin-login-surface"], .v2board-auth-box',
    visualRetired: true,
  },
  {
    label: 'user-login-ja-jp',
    locale: 'ja-JP',
    path: '/login',
    visualRetired: true,
  },
  {
    label: 'user-register-rich-ja-jp',
    locale: 'ja-JP',
    path: '/register?code=INVITE2026',
    visualRetired: true,
  },
  {
    label: 'user-forget-ja-jp',
    locale: 'ja-JP',
    path: '/forgetpassword',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-dashboard-ja-jp',
    locale: 'ja-JP',
    path: '/dashboard',
    readySelector: dashboardShortcutSelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plans-ja-jp',
    locale: 'ja-JP',
    path: '/plan',
    readySelector: '[data-testid="plan-card"], .block-link-pop',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plan-checkout-ja-jp',
    locale: 'ja-JP',
    path: '/plan/1',
    readySelector: '#cashier',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-orders-ja-jp',
    locale: 'ja-JP',
    path: '/order',
    readySelector: '[data-testid="orders-table"] tbody tr, .ant-table-tbody tr',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-order-detail-ja-jp',
    locale: 'ja-JP',
    path: '/order/VISUAL2026110001',
    readySelector: orderDetailReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-node-ja-jp',
    locale: 'ja-JP',
    path: '/node',
    readySelector: userNodeRowsReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-traffic-ja-jp',
    locale: 'ja-JP',
    path: '/traffic',
    readySelector: userTrafficRowsReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-invite-ja-jp',
    locale: 'ja-JP',
    path: '/invite',
    readySelector: '[data-testid="invite-surface"], .ant-pagination',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-tickets-ja-jp',
    locale: 'ja-JP',
    path: '/ticket',
    readySelector: '[data-testid="ticket-table"]',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-ticket-detail-ja-jp',
    locale: 'ja-JP',
    path: '/ticket/7',
    readySelector: '[data-testid="ticket-reply-input"], .js-chat-input',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-knowledge-ja-jp',
    locale: 'ja-JP',
    path: '/knowledge',
    readySelector: '[data-testid="knowledge-item"], .list-group-item',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-profile-ja-jp',
    locale: 'ja-JP',
    path: '/profile',
    readySelector: '[data-testid="profile-page"], .ant-switch',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-dashboard-no-subscription-vi-vn',
    locale: 'vi-VN',
    noSubscription: true,
    path: '/dashboard',
    readySelector: dashboardEmptyPlanReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    expiredSubscription: true,
    label: 'user-dashboard-expired-subscription-vi-vn',
    locale: 'vi-VN',
    path: '/dashboard',
    readySelector: dashboardExpiredReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-dashboard-traffic-used-up-vi-vn',
    locale: 'vi-VN',
    path: '/dashboard',
    readySelector: dashboardTrafficUsedUpReadySelector,
    trafficUsedUp: true,
    visualRetired: true,
  },
  {
    authenticated: true,
    deviceLimitReached: true,
    label: 'user-dashboard-device-limit-reached-vi-vn',
    locale: 'vi-VN',
    path: '/dashboard',
    readySelector: dashboardProgressReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    bannedUser: true,
    label: 'user-dashboard-banned-vi-vn',
    locale: 'vi-VN',
    path: '/dashboard',
    readySelector: dashboardShortcutSelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    darkMode: true,
    label: 'user-dashboard-dark-vi-vn',
    locale: 'vi-VN',
    path: '/dashboard',
    readySelector: dashboardShortcutSelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plans-long-data-vi-vn',
    locale: 'vi-VN',
    longData: true,
    path: '/plan',
    postReadyDelay: 300,
    readySelector: '[data-testid="plan-card"], .block-link-pop',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plans-sold-out-vi-vn',
    locale: 'vi-VN',
    path: '/plan',
    readySelector:
      '[data-testid="plan-card"][aria-disabled="true"], .block-link-pop button[disabled]',
    soldOutPlans: true,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plan-checkout-non-renewable-vi-vn',
    locale: 'vi-VN',
    nonRenewablePlan: true,
    path: '/plan/1',
    readySelector: '[data-testid="plan-non-renewable"], .ant-result-info',
    visualRetired: true,
  },
  {
    authenticated: true,
    forceUserUnauthorized: true,
    label: 'user-dashboard-session-expired-vi-vn',
    locale: 'vi-VN',
    path: '/dashboard',
    postReadyDelay: 300,
    readySelector: '[data-testid="admin-login-surface"], .v2board-auth-box',
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyPlans: true,
    label: 'user-plans-empty-vi-vn',
    locale: 'vi-VN',
    path: '/plan',
    readySelector: '[data-testid="plan-empty"], .spinner-grow',
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyOrders: true,
    label: 'user-orders-empty-vi-vn',
    locale: 'vi-VN',
    path: '/order',
    readySelector: '[data-testid="orders-empty"], .ant-table-placeholder .ant-empty',
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyServers: true,
    label: 'user-node-empty-vi-vn',
    locale: 'vi-VN',
    path: '/node',
    readySelector: userNodeEmptyReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyTickets: true,
    label: 'user-tickets-empty-vi-vn',
    locale: 'vi-VN',
    path: '/ticket',
    readySelector: '[data-testid="ticket-empty"]',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-orders-long-data-vi-vn',
    locale: 'vi-VN',
    longData: true,
    path: '/order',
    postReadyDelay: 300,
    readySelector: '[data-testid="orders-table"] tbody tr, .ant-table-tbody tr',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-node-long-data-vi-vn',
    locale: 'vi-VN',
    longData: true,
    path: '/node',
    postReadyDelay: 300,
    readySelector: userNodeRowsReadySelector,
    visualRetired: true,
  },
  {
    label: 'user-home-root-vi-vn',
    locale: 'vi-VN',
    path: '/',
    readySelector: '[data-testid="admin-login-surface"], .v2board-auth-box',
    visualRetired: true,
  },
  {
    label: 'user-login-vi-vn',
    locale: 'vi-VN',
    path: '/login',
    visualRetired: true,
  },
  {
    label: 'user-register-rich-vi-vn',
    locale: 'vi-VN',
    path: '/register?code=INVITE2026',
    visualRetired: true,
  },
  {
    label: 'user-forget-vi-vn',
    locale: 'vi-VN',
    path: '/forgetpassword',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-dashboard-vi-vn',
    locale: 'vi-VN',
    path: '/dashboard',
    readySelector: dashboardShortcutSelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plans-vi-vn',
    locale: 'vi-VN',
    path: '/plan',
    readySelector: '[data-testid="plan-card"], .block-link-pop',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plan-checkout-vi-vn',
    locale: 'vi-VN',
    path: '/plan/1',
    readySelector: '#cashier',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-orders-vi-vn',
    locale: 'vi-VN',
    path: '/order',
    readySelector: '[data-testid="orders-table"] tbody tr, .ant-table-tbody tr',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-order-detail-vi-vn',
    locale: 'vi-VN',
    path: '/order/VISUAL2026110001',
    readySelector: orderDetailReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-node-vi-vn',
    locale: 'vi-VN',
    path: '/node',
    readySelector: userNodeRowsReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-traffic-vi-vn',
    locale: 'vi-VN',
    path: '/traffic',
    readySelector: userTrafficRowsReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-invite-vi-vn',
    locale: 'vi-VN',
    path: '/invite',
    readySelector: '[data-testid="invite-surface"], .ant-pagination',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-tickets-vi-vn',
    locale: 'vi-VN',
    path: '/ticket',
    readySelector: '[data-testid="ticket-table"]',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-ticket-detail-vi-vn',
    locale: 'vi-VN',
    path: '/ticket/7',
    readySelector: '[data-testid="ticket-reply-input"], .js-chat-input',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-knowledge-vi-vn',
    locale: 'vi-VN',
    path: '/knowledge',
    readySelector: '[data-testid="knowledge-item"], .list-group-item',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-profile-vi-vn',
    locale: 'vi-VN',
    path: '/profile',
    readySelector: '[data-testid="profile-page"], .ant-switch',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-dashboard-no-subscription-ko-kr',
    locale: 'ko-KR',
    noSubscription: true,
    path: '/dashboard',
    readySelector: dashboardEmptyPlanReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    expiredSubscription: true,
    label: 'user-dashboard-expired-subscription-ko-kr',
    locale: 'ko-KR',
    path: '/dashboard',
    readySelector: dashboardExpiredReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-dashboard-traffic-used-up-ko-kr',
    locale: 'ko-KR',
    path: '/dashboard',
    readySelector: dashboardTrafficUsedUpReadySelector,
    trafficUsedUp: true,
    visualRetired: true,
  },
  {
    authenticated: true,
    deviceLimitReached: true,
    label: 'user-dashboard-device-limit-reached-ko-kr',
    locale: 'ko-KR',
    path: '/dashboard',
    readySelector: dashboardProgressReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    bannedUser: true,
    label: 'user-dashboard-banned-ko-kr',
    locale: 'ko-KR',
    path: '/dashboard',
    readySelector: dashboardShortcutSelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    darkMode: true,
    label: 'user-dashboard-dark-ko-kr',
    locale: 'ko-KR',
    path: '/dashboard',
    readySelector: dashboardShortcutSelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plans-long-data-ko-kr',
    locale: 'ko-KR',
    longData: true,
    path: '/plan',
    postReadyDelay: 300,
    readySelector: '[data-testid="plan-card"], .block-link-pop',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plans-sold-out-ko-kr',
    locale: 'ko-KR',
    path: '/plan',
    readySelector:
      '[data-testid="plan-card"][aria-disabled="true"], .block-link-pop button[disabled]',
    soldOutPlans: true,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plan-checkout-non-renewable-ko-kr',
    locale: 'ko-KR',
    nonRenewablePlan: true,
    path: '/plan/1',
    readySelector: '[data-testid="plan-non-renewable"], .ant-result-info',
    visualRetired: true,
  },
  {
    authenticated: true,
    forceUserUnauthorized: true,
    label: 'user-dashboard-session-expired-ko-kr',
    locale: 'ko-KR',
    path: '/dashboard',
    postReadyDelay: 300,
    readySelector: '[data-testid="admin-login-surface"], .v2board-auth-box',
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyPlans: true,
    label: 'user-plans-empty-ko-kr',
    locale: 'ko-KR',
    path: '/plan',
    readySelector: '[data-testid="plan-empty"], .spinner-grow',
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyOrders: true,
    label: 'user-orders-empty-ko-kr',
    locale: 'ko-KR',
    path: '/order',
    readySelector: '[data-testid="orders-empty"], .ant-table-placeholder .ant-empty',
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyServers: true,
    label: 'user-node-empty-ko-kr',
    locale: 'ko-KR',
    path: '/node',
    readySelector: userNodeEmptyReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    emptyTickets: true,
    label: 'user-tickets-empty-ko-kr',
    locale: 'ko-KR',
    path: '/ticket',
    readySelector: '[data-testid="ticket-empty"]',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-orders-long-data-ko-kr',
    locale: 'ko-KR',
    longData: true,
    path: '/order',
    postReadyDelay: 300,
    readySelector: '[data-testid="orders-table"] tbody tr, .ant-table-tbody tr',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-node-long-data-ko-kr',
    locale: 'ko-KR',
    longData: true,
    path: '/node',
    postReadyDelay: 300,
    readySelector: userNodeRowsReadySelector,
    visualRetired: true,
  },
  {
    label: 'user-home-root-ko-kr',
    locale: 'ko-KR',
    path: '/',
    readySelector: '[data-testid="admin-login-surface"], .v2board-auth-box',
    visualRetired: true,
  },
  {
    label: 'user-login-ko-kr',
    locale: 'ko-KR',
    path: '/login',
    visualRetired: true,
  },
  {
    label: 'user-register-rich-ko-kr',
    locale: 'ko-KR',
    path: '/register?code=INVITE2026',
    visualRetired: true,
  },
  {
    label: 'user-forget-ko-kr',
    locale: 'ko-KR',
    path: '/forgetpassword',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-dashboard-ko-kr',
    locale: 'ko-KR',
    path: '/dashboard',
    readySelector: dashboardShortcutSelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plans-ko-kr',
    locale: 'ko-KR',
    path: '/plan',
    readySelector: '[data-testid="plan-card"], .block-link-pop',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-plan-checkout-ko-kr',
    locale: 'ko-KR',
    path: '/plan/1',
    readySelector: '#cashier',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-orders-ko-kr',
    locale: 'ko-KR',
    path: '/order',
    readySelector: '[data-testid="orders-table"] tbody tr, .ant-table-tbody tr',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-order-detail-ko-kr',
    locale: 'ko-KR',
    path: '/order/VISUAL2026110001',
    readySelector: orderDetailReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-node-ko-kr',
    locale: 'ko-KR',
    path: '/node',
    readySelector: userNodeRowsReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-traffic-ko-kr',
    locale: 'ko-KR',
    path: '/traffic',
    readySelector: userTrafficRowsReadySelector,
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-invite-ko-kr',
    locale: 'ko-KR',
    path: '/invite',
    readySelector: '[data-testid="invite-surface"], .ant-pagination',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-tickets-ko-kr',
    locale: 'ko-KR',
    path: '/ticket',
    readySelector: '[data-testid="ticket-table"]',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-ticket-detail-ko-kr',
    locale: 'ko-KR',
    path: '/ticket/7',
    readySelector: '[data-testid="ticket-reply-input"], .js-chat-input',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-knowledge-ko-kr',
    locale: 'ko-KR',
    path: '/knowledge',
    readySelector: '[data-testid="knowledge-item"], .list-group-item',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'user-profile-ko-kr',
    locale: 'ko-KR',
    path: '/profile',
    readySelector: '[data-testid="profile-page"], .ant-switch',
    visualRetired: true,
  },
  {
    authenticated: true,
    label: 'admin-dashboard',
    visualRetired: true,
    path: '/dashboard',
    postReadyDelay: 800,
    readySelector: '[role="alert"], .alert.alert-danger',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    authenticated: true,
    forceAdminUnauthorized: true,
    forceCheckLoginNotAdmin: true,
    label: 'admin-dashboard-session-expired',
    visualRetired: true,
    path: '/dashboard',
    postReadyDelay: 300,
    readySelector: '[data-testid="admin-login-surface"], .v2board-auth-box',
  },
  {
    authenticated: true,
    darkMode: true,
    label: 'admin-dashboard-dark',
    visualRetired: true,
    path: '/dashboard',
    postReadyDelay: 800,
    readySelector: '[role="alert"], .alert.alert-danger',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    authenticated: true,
    label: 'admin-plans',
    visualRetired: true,
    path: '/plan',
    readySelector: '[data-slot="table-row"], .ant-table-tbody tr',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  // §W1: enter the path-routed admin app through the legacy
  // `/{admin_path}#/plan` URL to pin the §10.3 boot translator under the admin
  // basename. No warmup: the translator only runs at boot, so the scenario
  // must land directly on the hash entry URL (auth is seeded by the fixture
  // init script).
  {
    authenticated: true,
    label: 'admin-plan-legacy-hash-entry',
    legacyHashEntry: true,
    path: '/plan',
    readySelector: '[data-slot="table-row"], .ant-table-tbody tr',
    visualRetired: true,
  },
  {
    adminPlansTimeout: true,
    authenticated: true,
    label: 'admin-plans-timeout',
    visualRetired: true,
    path: '/plan',
    postReadyDelay: 800,
    readySelector: '[data-slot="table"], .ant-table',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    authenticated: true,
    label: 'admin-orders',
    visualRetired: true,
    path: '/order',
    readySelector: '[data-slot="table-row"], .ant-table-tbody tr',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    authenticated: true,
    label: 'admin-orders-long-data',
    visualRetired: true,
    longData: true,
    path: '/order',
    postReadyDelay: 500,
    readySelector: '[data-slot="table-row"], .ant-table-tbody tr',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    adminOrdersHttpError: true,
    authenticated: true,
    label: 'admin-orders-api-500',
    visualRetired: true,
    path: '/order',
    postReadyDelay: 500,
    readySelector: '[data-slot="table"], .ant-table',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    adminOrdersTimeout: true,
    authenticated: true,
    label: 'admin-orders-timeout',
    visualRetired: true,
    path: '/order',
    postReadyDelay: 800,
    readySelector: '[data-slot="table"], .ant-table',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    authenticated: true,
    label: 'admin-users',
    visualRetired: true,
    path: '/user',
    readySelector: '[data-slot="table-row"], .ant-table-tbody tr',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    adminUsersTimeout: true,
    authenticated: true,
    label: 'admin-users-timeout',
    visualRetired: true,
    path: '/user',
    postReadyDelay: 800,
    readySelector: '[data-slot="table"], .ant-table',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    adminUsersHttpError: true,
    authenticated: true,
    label: 'admin-users-api-500',
    visualRetired: true,
    path: '/user',
    postReadyDelay: 500,
    readySelector: '[data-slot="table"], .ant-table',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    adminTicketsTimeout: true,
    authenticated: true,
    label: 'admin-tickets-timeout',
    visualRetired: true,
    path: '/ticket',
    postReadyDelay: 800,
    readySelector: '[data-slot="table"], .ant-table',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    authenticated: true,
    label: 'admin-users-long-data',
    visualRetired: true,
    longData: true,
    path: '/user',
    postReadyDelay: 500,
    readySelector: '[data-slot="table-row"], .ant-table-tbody tr',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    authenticated: true,
    label: 'admin-tickets',
    visualRetired: true,
    path: '/ticket',
    readySelector: '[data-slot="table-row"], .ant-table-tbody tr',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    authenticated: true,
    label: 'admin-ticket-detail',
    visualRetired: true,
    path: '/ticket/7',
    readySelector: '[data-testid="ticket-reply-input"], .js-chat-input',
    seedLegacyAdminStore: true,
    warmupPath: '/ticket',
  },
  {
    authenticated: true,
    label: 'admin-config',
    visualRetired: true,
    path: '/config/system',
    readySelector: '[data-testid^="config-tab-"], .ant-tabs-tab',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    authenticated: true,
    label: 'admin-system',
    visualRetired: true,
    path: '/queue',
    readySelector: '[data-slot="table-row"], .ant-table-tbody tr',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    authenticated: true,
    label: 'admin-server-groups',
    visualRetired: true,
    path: '/server/group',
    readySelector: '[data-slot="table-row"], .ant-table-tbody tr',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    authenticated: true,
    label: 'admin-server-manage',
    visualRetired: true,
    path: '/server/manage',
    postReadyDelay: 300,
    readySelector: '[data-slot="table-row"], .ant-table-tbody tr',
    seedLegacyAdminStore: true,
    warmupPath: '/server/group',
  },
  {
    authenticated: true,
    label: 'admin-server-manage-long-data',
    visualRetired: true,
    longData: true,
    path: '/server/manage',
    postReadyDelay: 500,
    readySelector: '[data-slot="table-row"], .ant-table-tbody tr',
    seedLegacyAdminStore: true,
    warmupPath: '/server/group',
  },
  {
    adminServerManageTimeout: true,
    authenticated: true,
    label: 'admin-server-manage-timeout',
    visualRetired: true,
    path: '/server/manage',
    postReadyDelay: 800,
    readySelector: '[data-slot="table"], .ant-table',
    seedLegacyAdminStore: true,
    warmupPath: '/server/group',
  },
  {
    authenticated: true,
    label: 'admin-server-routes',
    visualRetired: true,
    path: '/server/route',
    readySelector: '[data-slot="table-row"], .ant-table-tbody tr',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    authenticated: true,
    label: 'admin-payments',
    visualRetired: true,
    path: '/config/payment',
    readySelector: '[data-slot="table-row"], .ant-table-tbody tr',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    adminPaymentsTimeout: true,
    authenticated: true,
    label: 'admin-payments-timeout',
    visualRetired: true,
    path: '/config/payment',
    postReadyDelay: 800,
    readySelector: '[data-slot="table"], .ant-table',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    authenticated: true,
    label: 'admin-coupons',
    visualRetired: true,
    path: '/coupon',
    readySelector: '[data-slot="table-row"], .ant-table-tbody tr',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    adminCouponsTimeout: true,
    authenticated: true,
    label: 'admin-coupons-timeout',
    visualRetired: true,
    path: '/coupon',
    postReadyDelay: 800,
    readySelector: '[data-slot="table"], .ant-table',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    authenticated: true,
    label: 'admin-giftcards',
    visualRetired: true,
    path: '/giftcard',
    readySelector: '[data-slot="table-row"], .ant-table-tbody tr',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    adminGiftcardsTimeout: true,
    authenticated: true,
    label: 'admin-giftcards-timeout',
    visualRetired: true,
    path: '/giftcard',
    postReadyDelay: 800,
    readySelector: '[data-slot="table"], .ant-table',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    authenticated: true,
    label: 'admin-notices',
    visualRetired: true,
    path: '/notice',
    readySelector: '[data-slot="table-row"], .ant-table-tbody tr',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    adminNoticesTimeout: true,
    authenticated: true,
    label: 'admin-notices-timeout',
    visualRetired: true,
    path: '/notice',
    postReadyDelay: 800,
    readySelector: '[data-slot="table"], .ant-table',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    authenticated: true,
    label: 'admin-knowledge',
    visualRetired: true,
    path: '/knowledge',
    readySelector: '[data-slot="table-row"], .ant-table-tbody tr',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    adminKnowledgeTimeout: true,
    authenticated: true,
    label: 'admin-knowledge-timeout',
    visualRetired: true,
    path: '/knowledge',
    postReadyDelay: 800,
    readySelector: '[data-slot="table"], .ant-table',
    seedLegacyAdminStore: true,
    warmupPath: '/login',
  },
  {
    label: 'admin-root',
    path: '/',
    readySelector: '[data-testid="admin-login-surface"], .v2board-auth-box',
    visualRetired: true,
  },
  { label: 'admin-login', path: '/login', visualRetired: true },
];

export const scenariosByLabel = new Map(scenarios.map((s) => [s.label, s]));

export function getScenario(label) {
  const s = scenariosByLabel.get(label);
  if (!s) throw new Error('Unknown scenario ' + label);
  return s;
}
