-- V2Board native PostgreSQL 18 final-state baseline.
-- This lineage is intentionally independent from the retained MySQL migrations.

-- Installation identity is created by the lifecycle bootstrap, not by this
-- ordinary runtime migration. The local development seed is the sole exception.
CREATE TABLE v2_system_installation (
    singleton SMALLINT PRIMARY KEY CHECK (singleton = 1),
    installation_id UUID NOT NULL UNIQUE,
    lineage TEXT NOT NULL CHECK (lineage IN ('native', 'legacy_migrated')),
    state TEXT NOT NULL CHECK (state IN ('pending', 'active', 'retired')),
    created_at BIGINT NOT NULL,
    activated_at BIGINT,
    source_fingerprint_sha256 TEXT,
    CONSTRAINT chk_system_installation_activation CHECK (
        (state = 'pending' AND activated_at IS NULL)
        OR (state IN ('active', 'retired') AND activated_at IS NOT NULL)
    ),
    CONSTRAINT chk_system_installation_source_fingerprint CHECK (
        source_fingerprint_sha256 IS NULL
        OR source_fingerprint_sha256 ~ '^[0-9a-f]{64}$'
    )
);

CREATE FUNCTION v2_guard_system_installation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'installation identity cannot be deleted';
    END IF;
    IF NEW.singleton IS DISTINCT FROM OLD.singleton
       OR NEW.installation_id IS DISTINCT FROM OLD.installation_id
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'installation identity cannot be changed';
    END IF;
    IF NEW.lineage IS DISTINCT FROM OLD.lineage
       AND NOT (OLD.lineage = 'legacy_migrated' AND NEW.lineage = 'native') THEN
        RAISE EXCEPTION 'invalid installation lineage transition: % -> %', OLD.lineage, NEW.lineage;
    END IF;
    IF NEW.state IS DISTINCT FROM OLD.state
       AND NOT (
           (OLD.state = 'pending' AND NEW.state = 'active')
           OR (OLD.state = 'active' AND NEW.state = 'retired')
       ) THEN
        RAISE EXCEPTION 'invalid installation state transition: % -> %', OLD.state, NEW.state;
    END IF;
    IF OLD.activated_at IS NOT NULL
       AND NEW.activated_at IS DISTINCT FROM OLD.activated_at THEN
        RAISE EXCEPTION 'installation activation time cannot be changed';
    END IF;
    IF OLD.source_fingerprint_sha256 IS NOT NULL
       AND NEW.source_fingerprint_sha256 IS DISTINCT FROM OLD.source_fingerprint_sha256 THEN
        RAISE EXCEPTION 'installation source fingerprint cannot be changed once recorded';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_system_installation_guard
BEFORE UPDATE OR DELETE ON v2_system_installation
FOR EACH ROW EXECUTE FUNCTION v2_guard_system_installation();

CREATE TABLE v2_server_group (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE v2_plan (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INTEGER NOT NULL REFERENCES v2_server_group(id) ON DELETE RESTRICT,
    transfer_enable BIGINT NOT NULL,
    device_limit INTEGER,
    name VARCHAR(255) NOT NULL,
    speed_limit INTEGER,
    show SMALLINT NOT NULL DEFAULT 0,
    sort INTEGER,
    renew SMALLINT NOT NULL DEFAULT 1,
    content TEXT,
    month_price INTEGER,
    quarter_price INTEGER,
    half_year_price INTEGER,
    year_price INTEGER,
    two_year_price INTEGER,
    three_year_price INTEGER,
    onetime_price INTEGER,
    reset_price INTEGER,
    reset_traffic_method SMALLINT,
    capacity_limit INTEGER,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);
CREATE INDEX idx_plan_group_id ON v2_plan(group_id);

CREATE TABLE v2_payment (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(32) NOT NULL,
    payment VARCHAR(16) NOT NULL,
    name VARCHAR(255) NOT NULL,
    icon VARCHAR(255),
    config JSONB NOT NULL,
    notify_domain VARCHAR(128),
    handling_fee_fixed INTEGER,
    handling_fee_percent NUMERIC(5,2),
    enable SMALLINT NOT NULL DEFAULT 0,
    archived_at BIGINT,
    sort INTEGER,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT uniq_payment_driver_uuid UNIQUE (payment, uuid)
);
CREATE INDEX idx_payment_archived ON v2_payment(archived_at, id);

CREATE TABLE v2_coupon (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    type SMALLINT NOT NULL,
    value INTEGER NOT NULL,
    show SMALLINT NOT NULL DEFAULT 0,
    limit_use INTEGER,
    limit_use_with_user INTEGER,
    limit_plan_ids JSONB,
    limit_period JSONB,
    started_at BIGINT NOT NULL,
    ended_at BIGINT NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT uniq_coupon_code UNIQUE (code),
    CONSTRAINT chk_coupon_limit_plan_ids_array
        CHECK (limit_plan_ids IS NULL OR jsonb_typeof(limit_plan_ids) = 'array'),
    CONSTRAINT chk_coupon_limit_period_array
        CHECK (limit_period IS NULL OR jsonb_typeof(limit_period) = 'array')
);
-- Legacy utf8mb4_unicode_ci treated human-entered redemption codes as
-- case-insensitive. Keep the submitted spelling for display while preventing
-- a second spelling that would have represented the same legacy code.
CREATE UNIQUE INDEX uniq_coupon_code_canonical ON v2_coupon((lower(code)));

CREATE TABLE v2_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invite_user_id BIGINT,
    telegram_id BIGINT,
    email VARCHAR(64) NOT NULL,
    password VARCHAR(255) NOT NULL,
    password_algo VARCHAR(10),
    password_salt VARCHAR(10),
    session_epoch BIGINT NOT NULL DEFAULT 0,
    traffic_epoch BIGINT NOT NULL DEFAULT 0,
    scheduled_traffic_reset_key VARCHAR(10),
    balance INTEGER NOT NULL DEFAULT 0,
    discount INTEGER,
    commission_type SMALLINT NOT NULL DEFAULT 0,
    commission_rate INTEGER,
    commission_balance INTEGER NOT NULL DEFAULT 0,
    t BIGINT NOT NULL DEFAULT 0,
    u BIGINT NOT NULL DEFAULT 0,
    d BIGINT NOT NULL DEFAULT 0,
    transfer_enable BIGINT NOT NULL DEFAULT 0,
    device_limit INTEGER,
    banned SMALLINT NOT NULL DEFAULT 0,
    is_admin SMALLINT NOT NULL DEFAULT 0,
    last_login_at BIGINT,
    is_staff SMALLINT NOT NULL DEFAULT 0,
    last_login_ip INTEGER,
    uuid VARCHAR(36) NOT NULL,
    group_id INTEGER REFERENCES v2_server_group(id) ON DELETE RESTRICT,
    plan_id INTEGER REFERENCES v2_plan(id) ON DELETE RESTRICT,
    speed_limit INTEGER,
    auto_renewal SMALLINT DEFAULT 0,
    remind_expire SMALLINT DEFAULT 1,
    remind_traffic SMALLINT DEFAULT 1,
    token VARCHAR(32) NOT NULL,
    expired_at BIGINT DEFAULT 0,
    remarks TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT uniq_user_email UNIQUE (email),
    CONSTRAINT uniq_user_token UNIQUE (token),
    CONSTRAINT fk_user_inviter FOREIGN KEY (invite_user_id)
        REFERENCES v2_user(id) ON DELETE SET NULL
);
CREATE INDEX idx_user_plan_id ON v2_user(plan_id);
-- Legacy MySQL's user-email uniqueness was case-insensitive. Preserve that
-- externally visible identity contract while retaining the submitted spelling
-- for display; the legacy converter must report broader collation collisions
-- before it reaches this index.
CREATE UNIQUE INDEX uniq_user_email_canonical ON v2_user((lower(btrim(email))));
CREATE INDEX idx_user_group_id ON v2_user(group_id);
CREATE INDEX idx_user_invite_user_id ON v2_user(invite_user_id);
CREATE INDEX idx_user_renewal_candidate ON v2_user(auto_renewal, expired_at, id);
CREATE INDEX idx_user_created_at ON v2_user(created_at);

CREATE TABLE v2_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invite_user_id BIGINT,
    user_id BIGINT NOT NULL REFERENCES v2_user(id) ON DELETE RESTRICT,
    plan_id INTEGER NOT NULL,
    referenced_plan_id INTEGER GENERATED ALWAYS AS (NULLIF(plan_id, 0)) STORED
        REFERENCES v2_plan(id) ON DELETE RESTRICT,
    coupon_id INTEGER,
    payment_id INTEGER,
    type INTEGER NOT NULL,
    period VARCHAR(255) NOT NULL,
    trade_no VARCHAR(36) NOT NULL,
    callback_no VARCHAR(255),
    callback_no_hash BYTEA,
    total_amount INTEGER NOT NULL,
    handling_amount INTEGER,
    discount_amount INTEGER,
    surplus_amount INTEGER,
    refund_amount INTEGER,
    balance_amount INTEGER,
    surplus_order_ids TEXT,
    status SMALLINT NOT NULL DEFAULT 0,
    commission_status SMALLINT NOT NULL DEFAULT 0,
    commission_balance INTEGER NOT NULL DEFAULT 0,
    actual_commission_balance INTEGER,
    paid_at BIGINT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    unfinished_user_id BIGINT GENERATED ALWAYS AS (
        CASE WHEN status IN (0, 1) THEN user_id ELSE NULL END
    ) STORED,
    CONSTRAINT uniq_order_trade_no UNIQUE (trade_no),
    CONSTRAINT chk_order_callback_hash_size
        CHECK (callback_no_hash IS NULL OR octet_length(callback_no_hash) = 32)
);
CREATE INDEX idx_order_user ON v2_order(user_id);
CREATE INDEX idx_order_user_status ON v2_order(user_id, status);
CREATE UNIQUE INDEX uniq_unfinished_order_per_user
    ON v2_order(user_id) WHERE status IN (0, 1);
CREATE INDEX idx_commission_claim ON v2_order(commission_status, id);
CREATE INDEX idx_order_payment_status ON v2_order(payment_id, status);
CREATE INDEX idx_order_status_id ON v2_order(status, id);
CREATE INDEX idx_order_referenced_plan ON v2_order(referenced_plan_id);
CREATE INDEX idx_order_coupon_user_status ON v2_order(coupon_id, user_id, status);
CREATE INDEX idx_order_created_at ON v2_order(created_at);
CREATE INDEX idx_order_paid_at ON v2_order(paid_at) WHERE paid_at IS NOT NULL;

CREATE TABLE v2_commission_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invite_user_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    trade_no VARCHAR(36) NOT NULL,
    order_amount INTEGER NOT NULL,
    get_amount INTEGER NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);
CREATE INDEX idx_commission_log_inviter ON v2_commission_log(invite_user_id, created_at DESC);
CREATE INDEX idx_commission_log_created_at ON v2_commission_log(created_at);

CREATE TABLE v2_invite_code (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES v2_user(id) ON DELETE CASCADE,
    code VARCHAR(32) NOT NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    pv INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT uniq_invite_code UNIQUE (code)
);
CREATE UNIQUE INDEX uniq_invite_code_canonical ON v2_invite_code((lower(code)));
CREATE INDEX idx_invite_user_status ON v2_invite_code(user_id, status);

CREATE TABLE v2_giftcard (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    type SMALLINT NOT NULL,
    value INTEGER,
    plan_id INTEGER REFERENCES v2_plan(id) ON DELETE RESTRICT,
    limit_use INTEGER,
    started_at BIGINT NOT NULL,
    ended_at BIGINT NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT uniq_giftcard_code UNIQUE (code)
);
CREATE UNIQUE INDEX uniq_giftcard_code_canonical ON v2_giftcard((lower(code)));
CREATE INDEX idx_giftcard_plan_id ON v2_giftcard(plan_id);

CREATE TABLE v2_giftcard_redemption (
    giftcard_id INTEGER NOT NULL REFERENCES v2_giftcard(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES v2_user(id) ON DELETE CASCADE,
    created_at BIGINT NOT NULL,
    PRIMARY KEY (giftcard_id, user_id)
);
CREATE INDEX idx_giftcard_redemption_user ON v2_giftcard_redemption(user_id);

CREATE TABLE v2_payment_reconciliation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id INTEGER NOT NULL REFERENCES v2_payment(id) ON DELETE RESTRICT,
    provider VARCHAR(32) NOT NULL,
    trade_no VARCHAR(255) NOT NULL,
    trade_no_hash BYTEA NOT NULL CHECK (octet_length(trade_no_hash) = 32),
    callback_no VARCHAR(255) NOT NULL,
    callback_no_hash BYTEA NOT NULL CHECK (octet_length(callback_no_hash) = 32),
    reason VARCHAR(64) NOT NULL,
    order_status SMALLINT NOT NULL,
    expected_amount BIGINT NOT NULL,
    settled_amount BIGINT,
    occurrence_count INTEGER NOT NULL DEFAULT 1 CHECK (occurrence_count >= 0),
    first_seen_at BIGINT NOT NULL,
    last_seen_at BIGINT NOT NULL,
    resolved_at BIGINT,
    resolution VARCHAR(255),
    CONSTRAINT uniq_payment_reconciliation_callback
        UNIQUE (payment_id, callback_no_hash)
);
CREATE INDEX idx_payment_reconciliation_open
    ON v2_payment_reconciliation(resolved_at, first_seen_at);
CREATE INDEX idx_payment_reconciliation_trade
    ON v2_payment_reconciliation(trade_no_hash);

CREATE TABLE v2_knowledge (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language VARCHAR(5) NOT NULL,
    category VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    sort INTEGER,
    show SMALLINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE v2_notice (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    show SMALLINT NOT NULL DEFAULT 0,
    img_url VARCHAR(255),
    tags JSONB CHECK (tags IS NULL OR jsonb_typeof(tags) = 'array'),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE v2_ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES v2_user(id) ON DELETE RESTRICT,
    subject VARCHAR(255) NOT NULL,
    level SMALLINT NOT NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    reply_status SMALLINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    open_user_id BIGINT GENERATED ALWAYS AS (
        CASE WHEN status = 0 THEN user_id ELSE NULL END
    ) STORED
);
CREATE UNIQUE INDEX uniq_ticket_open_user ON v2_ticket(user_id) WHERE status = 0;
CREATE INDEX idx_ticket_user_status ON v2_ticket(user_id, status);
CREATE INDEX idx_ticket_auto_close ON v2_ticket(status, reply_status, updated_at, id);

CREATE TABLE v2_ticket_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    ticket_id BIGINT NOT NULL REFERENCES v2_ticket(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);
CREATE INDEX idx_ticket_message_ticket_id_id ON v2_ticket_message(ticket_id, id);

CREATE TABLE v2_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    level VARCHAR(11),
    host VARCHAR(255),
    uri VARCHAR(255) NOT NULL,
    method VARCHAR(11) NOT NULL,
    data TEXT,
    ip VARCHAR(128),
    context TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);
CREATE INDEX idx_log_created_at ON v2_log(created_at);

CREATE TABLE v2_mail_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(512) NOT NULL,
    subject TEXT NOT NULL,
    template_name VARCHAR(255) NOT NULL,
    error TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);
CREATE INDEX idx_mail_log_created_at ON v2_mail_log(created_at, id);

CREATE TABLE v2_mail_outbox_batch (
    batch_key VARCHAR(64) PRIMARY KEY,
    payload_hash VARCHAR(64) NOT NULL,
    actor VARCHAR(512) NOT NULL,
    sender VARCHAR(512),
    template_name VARCHAR(255),
    subject TEXT,
    body TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE v2_mail_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_key VARCHAR(64) NOT NULL REFERENCES v2_mail_outbox_batch(batch_key) ON DELETE CASCADE,
    recipient VARCHAR(512) NOT NULL,
    message_id VARCHAR(255) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    available_at BIGINT NOT NULL,
    lease_token VARCHAR(36),
    lease_expires_at BIGINT,
    failed_at BIGINT,
    last_error TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT uniq_mail_outbox_batch_recipient UNIQUE (batch_key, recipient),
    CONSTRAINT uniq_mail_outbox_message_id UNIQUE (message_id)
);
CREATE INDEX idx_mail_outbox_claim ON v2_mail_outbox(failed_at, available_at, id);
CREATE INDEX idx_mail_outbox_lease ON v2_mail_outbox(lease_expires_at);

CREATE TABLE v2_stat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_at BIGINT NOT NULL,
    record_type VARCHAR(1) NOT NULL,
    order_count INTEGER NOT NULL,
    order_total BIGINT NOT NULL,
    commission_count INTEGER NOT NULL,
    commission_total BIGINT NOT NULL,
    paid_count INTEGER NOT NULL,
    paid_total BIGINT NOT NULL,
    register_count INTEGER NOT NULL,
    invite_count INTEGER NOT NULL,
    transfer_used_total VARCHAR(32) NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT uniq_stat_record_at UNIQUE (record_at)
);

CREATE TABLE v2_stat_server (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_id INTEGER NOT NULL,
    server_type VARCHAR(11) NOT NULL,
    u BIGINT NOT NULL,
    d BIGINT NOT NULL,
    record_type VARCHAR(1) NOT NULL,
    record_at BIGINT NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT uniq_stat_server_day UNIQUE (server_id, server_type, record_at)
);
CREATE INDEX idx_stat_server_record_at ON v2_stat_server(record_at);
CREATE INDEX idx_stat_server_id ON v2_stat_server(server_id);

CREATE TABLE v2_stat_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    server_rate NUMERIC(10,2) NOT NULL,
    u BIGINT NOT NULL,
    d BIGINT NOT NULL,
    record_type VARCHAR(2) NOT NULL,
    record_at BIGINT NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT uniq_stat_user_day UNIQUE (server_rate, user_id, record_at)
);
CREATE INDEX idx_stat_user_record_at ON v2_stat_user(record_at);
CREATE INDEX idx_stat_user_user_record_at ON v2_stat_user(user_id, record_at DESC);

CREATE TABLE v2_analytics_delivery_batch (
    batch_id UUID PRIMARY KEY,
    event_name TEXT NOT NULL CHECK (btrim(event_name) <> ''),
    schema_major SMALLINT NOT NULL CHECK (schema_major > 0),
    partition_month DATE NOT NULL CHECK (
        partition_month = date_trunc('month', partition_month)::date
    ),
    table_generation INTEGER NOT NULL CHECK (table_generation > 0),
    row_count INTEGER NOT NULL CHECK (row_count BETWEEN 1 AND 100000),
    content_sha256 TEXT NOT NULL CHECK (content_sha256 ~ '^[0-9a-f]{64}$'),
    insert_settings_sha256 TEXT NOT NULL CHECK (insert_settings_sha256 ~ '^[0-9a-f]{64}$'),
    state TEXT NOT NULL CHECK (state IN ('ready', 'publishing', 'published', 'quarantined')),
    lease_owner UUID,
    lease_expires_at BIGINT,
    attempt_count INTEGER NOT NULL CHECK (attempt_count > 0),
    published_at BIGINT,
    quarantined_at BIGINT,
    quarantine_reason TEXT,
    last_error TEXT,
    created_at BIGINT NOT NULL,
    CONSTRAINT chk_analytics_batch_state CHECK (
        (state = 'ready'
            AND lease_owner IS NULL AND lease_expires_at IS NULL
            AND published_at IS NULL AND quarantined_at IS NULL)
        OR (state = 'publishing'
            AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL
            AND published_at IS NULL AND quarantined_at IS NULL)
        OR (state = 'published'
            AND lease_owner IS NULL AND lease_expires_at IS NULL
            AND published_at IS NOT NULL AND quarantined_at IS NULL)
        OR (state = 'quarantined'
            AND lease_owner IS NULL AND lease_expires_at IS NULL
            AND published_at IS NULL AND quarantined_at IS NOT NULL
            AND quarantine_reason IS NOT NULL)
    ),
    CONSTRAINT chk_analytics_batch_terminal_time CHECK (
        published_at IS NULL OR quarantined_at IS NULL
    )
);
CREATE INDEX idx_analytics_batch_claim
    ON v2_analytics_delivery_batch(created_at, batch_id)
    WHERE published_at IS NULL AND quarantined_at IS NULL
      AND state IN ('ready', 'publishing');
CREATE INDEX idx_analytics_batch_lease
    ON v2_analytics_delivery_batch(lease_expires_at, created_at, batch_id)
    WHERE state = 'publishing' AND published_at IS NULL AND quarantined_at IS NULL;

CREATE TABLE v2_analytics_outbox (
    outbox_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL,
    event_name TEXT NOT NULL CHECK (btrim(event_name) <> ''),
    schema_major SMALLINT NOT NULL CHECK (schema_major > 0),
    report_key VARCHAR(64) NOT NULL CHECK (report_key <> ''),
    partition_month DATE NOT NULL CHECK (
        partition_month = date_trunc('month', partition_month)::date
    ),
    occurred_at BIGINT NOT NULL,
    payload JSONB NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
    payload_sha256 TEXT NOT NULL CHECK (payload_sha256 ~ '^[0-9a-f]{64}$'),
    table_generation INTEGER NOT NULL DEFAULT 1 CHECK (table_generation > 0),
    delivery_batch_id UUID REFERENCES v2_analytics_delivery_batch(batch_id) ON DELETE RESTRICT,
    batch_row_number INTEGER,
    published_at BIGINT,
    quarantined_at BIGINT,
    created_at BIGINT NOT NULL,
    CONSTRAINT uniq_analytics_event_id UNIQUE (event_id),
    CONSTRAINT uniq_analytics_batch_row UNIQUE (delivery_batch_id, batch_row_number),
    CONSTRAINT chk_analytics_event_id CHECK (event_id ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_analytics_batch_assignment CHECK (
        (delivery_batch_id IS NULL AND batch_row_number IS NULL)
        OR (delivery_batch_id IS NOT NULL AND batch_row_number >= 0)
    ),
    CONSTRAINT chk_analytics_outbox_terminal CHECK (
        (published_at IS NULL OR quarantined_at IS NULL)
        AND ((published_at IS NULL AND quarantined_at IS NULL) OR delivery_batch_id IS NOT NULL)
    )
);
CREATE INDEX idx_analytics_outbox_unpublished
    ON v2_analytics_outbox(outbox_id)
    WHERE published_at IS NULL AND quarantined_at IS NULL;
CREATE INDEX idx_analytics_outbox_backlog
    ON v2_analytics_outbox(created_at, outbox_id)
    WHERE published_at IS NULL AND quarantined_at IS NULL;
CREATE INDEX idx_analytics_outbox_published_prune
    ON v2_analytics_outbox(published_at, outbox_id)
    WHERE published_at IS NOT NULL AND quarantined_at IS NULL;
CREATE INDEX idx_analytics_outbox_unbatched_claim
    ON v2_analytics_outbox(
        event_name, schema_major, partition_month, table_generation, outbox_id
    )
    WHERE published_at IS NULL AND quarantined_at IS NULL AND delivery_batch_id IS NULL;

CREATE TABLE v2_server_traffic_report (
    report_key VARCHAR(64) PRIMARY KEY,
    payload_hash VARCHAR(64) NOT NULL CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    node_id INTEGER NOT NULL CHECK (node_id > 0),
    node_type VARCHAR(32) NOT NULL CHECK (node_type <> ''),
    rate_text TEXT NOT NULL CHECK (btrim(rate_text) <> ''),
    rate_decimal_10_2 NUMERIC(10,2) NOT NULL CHECK (rate_decimal_10_2 >= 0),
    identity_kind TEXT NOT NULL CHECK (identity_kind IN ('explicit', 'implicit')),
    accepted_at BIGINT NOT NULL,
    accounting_date DATE NOT NULL,
    applied_at BIGINT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT chk_traffic_report_applied_after_acceptance CHECK (
        applied_at IS NULL OR applied_at >= accepted_at
    )
);
CREATE INDEX idx_traffic_report_claim
    ON v2_server_traffic_report(created_at, report_key)
    WHERE applied_at IS NULL;
CREATE INDEX idx_traffic_report_retention
    ON v2_server_traffic_report(applied_at, report_key)
    WHERE applied_at IS NOT NULL;

CREATE TABLE v2_server_traffic_report_item (
    report_key VARCHAR(64) NOT NULL
        REFERENCES v2_server_traffic_report(report_key) ON DELETE CASCADE,
    -- Deliberately not an FK: the API proves authorization while accepting the
    -- report, then a concurrent administrative user deletion is represented by
    -- the worker's durable `missing_user` accounting outcome instead of making
    -- user deletion depend on relay timing.
    user_id BIGINT NOT NULL,
    traffic_epoch BIGINT NOT NULL DEFAULT 0,
    raw_u BIGINT NOT NULL CHECK (raw_u >= 0),
    raw_d BIGINT NOT NULL CHECK (raw_d >= 0),
    charged_u BIGINT NOT NULL CHECK (charged_u >= 0),
    charged_d BIGINT NOT NULL CHECK (charged_d >= 0),
    PRIMARY KEY (report_key, user_id)
);
CREATE INDEX idx_traffic_report_item_user ON v2_server_traffic_report_item(user_id);

CREATE TABLE v2_server_credential (
    node_type VARCHAR(32) NOT NULL,
    node_id INTEGER NOT NULL,
    credential_epoch BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (node_type, node_id)
);

CREATE TABLE v2_server_route (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remarks VARCHAR(255) NOT NULL,
    match JSONB NOT NULL,
    action VARCHAR(11) NOT NULL,
    action_value JSONB,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE v2_server_shadowsocks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id JSONB NOT NULL CHECK (jsonb_typeof(group_id) = 'array' AND jsonb_array_length(group_id) > 0),
    route_id JSONB,
    parent_id INTEGER,
    tags JSONB,
    name VARCHAR(255) NOT NULL,
    rate VARCHAR(11) NOT NULL,
    host VARCHAR(255) NOT NULL,
    port VARCHAR(11) NOT NULL,
    server_port INTEGER NOT NULL,
    cipher VARCHAR(255) NOT NULL,
    obfs VARCHAR(11),
    obfs_settings JSONB,
    show SMALLINT NOT NULL DEFAULT 0,
    sort INTEGER,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE v2_server_vmess (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id JSONB NOT NULL CHECK (jsonb_typeof(group_id) = 'array' AND jsonb_array_length(group_id) > 0),
    route_id JSONB,
    name VARCHAR(255) NOT NULL,
    parent_id INTEGER,
    host VARCHAR(255) NOT NULL,
    port VARCHAR(11) NOT NULL,
    server_port INTEGER NOT NULL,
    tls SMALLINT NOT NULL DEFAULT 0,
    tags JSONB,
    rate VARCHAR(11) NOT NULL,
    network VARCHAR(11) NOT NULL,
    rules JSONB,
    "networkSettings" JSONB,
    "tlsSettings" JSONB,
    "ruleSettings" JSONB,
    "dnsSettings" JSONB,
    show SMALLINT NOT NULL DEFAULT 0,
    sort INTEGER,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE v2_server_trojan (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id JSONB NOT NULL CHECK (jsonb_typeof(group_id) = 'array' AND jsonb_array_length(group_id) > 0),
    route_id JSONB,
    parent_id INTEGER,
    tags JSONB,
    name VARCHAR(255) NOT NULL,
    rate VARCHAR(11) NOT NULL,
    host VARCHAR(255) NOT NULL,
    port VARCHAR(11) NOT NULL,
    server_port INTEGER NOT NULL,
    network VARCHAR(11),
    network_settings JSONB,
    allow_insecure SMALLINT NOT NULL DEFAULT 0,
    server_name VARCHAR(255),
    show SMALLINT NOT NULL DEFAULT 0,
    sort INTEGER,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE v2_server_tuic (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id JSONB NOT NULL CHECK (jsonb_typeof(group_id) = 'array' AND jsonb_array_length(group_id) > 0),
    route_id JSONB,
    name VARCHAR(255) NOT NULL,
    parent_id INTEGER,
    host VARCHAR(255) NOT NULL,
    port VARCHAR(11) NOT NULL,
    server_port INTEGER NOT NULL,
    tags JSONB,
    rate VARCHAR(11) NOT NULL,
    show SMALLINT NOT NULL DEFAULT 0,
    sort INTEGER,
    server_name VARCHAR(64),
    insecure SMALLINT NOT NULL DEFAULT 0,
    disable_sni SMALLINT NOT NULL DEFAULT 0,
    udp_relay_mode VARCHAR(64),
    zero_rtt_handshake SMALLINT NOT NULL DEFAULT 0,
    congestion_control VARCHAR(64),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE v2_server_hysteria (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL,
    group_id JSONB NOT NULL CHECK (jsonb_typeof(group_id) = 'array' AND jsonb_array_length(group_id) > 0),
    route_id JSONB,
    name VARCHAR(255) NOT NULL,
    parent_id INTEGER,
    host VARCHAR(255) NOT NULL,
    port VARCHAR(11) NOT NULL,
    server_port INTEGER NOT NULL,
    tags JSONB,
    rate VARCHAR(11) NOT NULL,
    show SMALLINT NOT NULL DEFAULT 0,
    sort INTEGER,
    up_mbps INTEGER NOT NULL,
    down_mbps INTEGER NOT NULL,
    obfs VARCHAR(64),
    obfs_password VARCHAR(255),
    server_name VARCHAR(64),
    insecure SMALLINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE v2_server_vless (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id JSONB NOT NULL CHECK (jsonb_typeof(group_id) = 'array' AND jsonb_array_length(group_id) > 0),
    route_id JSONB,
    name VARCHAR(255) NOT NULL,
    parent_id INTEGER,
    host VARCHAR(255) NOT NULL,
    port INTEGER NOT NULL,
    server_port INTEGER NOT NULL,
    tls SMALLINT NOT NULL,
    tls_settings JSONB,
    flow VARCHAR(64),
    network VARCHAR(11) NOT NULL,
    network_settings JSONB,
    encryption VARCHAR(64),
    encryption_settings JSONB,
    tags JSONB,
    rate VARCHAR(11) NOT NULL,
    show SMALLINT NOT NULL DEFAULT 0,
    sort INTEGER,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE v2_server_anytls (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id JSONB NOT NULL CHECK (jsonb_typeof(group_id) = 'array' AND jsonb_array_length(group_id) > 0),
    route_id JSONB,
    name VARCHAR(255) NOT NULL,
    parent_id INTEGER,
    host VARCHAR(255) NOT NULL,
    port VARCHAR(11) NOT NULL,
    server_port INTEGER NOT NULL,
    tags JSONB,
    rate VARCHAR(11) NOT NULL,
    show SMALLINT NOT NULL DEFAULT 0,
    sort INTEGER,
    server_name VARCHAR(64),
    insecure SMALLINT NOT NULL DEFAULT 0,
    padding_scheme JSONB,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE v2_server_v2node (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id JSONB NOT NULL CHECK (jsonb_typeof(group_id) = 'array' AND jsonb_array_length(group_id) > 0),
    route_id JSONB,
    name VARCHAR(255) NOT NULL,
    parent_id INTEGER,
    host VARCHAR(255) NOT NULL,
    listen_ip VARCHAR(255) NOT NULL DEFAULT '0.0.0.0',
    port VARCHAR(11) NOT NULL,
    server_port INTEGER NOT NULL,
    tags JSONB,
    rate VARCHAR(11) NOT NULL,
    show SMALLINT NOT NULL DEFAULT 0,
    sort INTEGER,
    protocol VARCHAR(24) NOT NULL,
    tls SMALLINT NOT NULL,
    tls_settings JSONB,
    flow VARCHAR(64),
    network VARCHAR(11) NOT NULL,
    network_settings JSONB,
    encryption VARCHAR(64),
    encryption_settings JSONB,
    disable_sni SMALLINT NOT NULL DEFAULT 0,
    udp_relay_mode VARCHAR(64),
    zero_rtt_handshake SMALLINT NOT NULL DEFAULT 0,
    congestion_control VARCHAR(64),
    cipher VARCHAR(64),
    up_mbps INTEGER NOT NULL,
    down_mbps INTEGER NOT NULL,
    obfs VARCHAR(64),
    obfs_password VARCHAR(255),
    padding_scheme JSONB,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);
