-- Preload/table phase of the single V2Board PostgreSQL 18 first-release
-- baseline. 0002 completes the business constraints and indexes.

-- One immutable identity binds the PostgreSQL installation to its ClickHouse
-- projection and runtime configuration. Import/install tooling creates the
-- complete row directly.
CREATE TABLE system_installation (
    singleton SMALLINT PRIMARY KEY CHECK (singleton = 1),
    installation_id UUID NOT NULL UNIQUE,
    created_at BIGINT NOT NULL
);

CREATE FUNCTION guard_system_installation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'installation identity cannot be deleted';
    END IF;
    IF NEW.singleton IS DISTINCT FROM OLD.singleton
       OR NEW.installation_id IS DISTINCT FROM OLD.installation_id
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'installation identity cannot be changed';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_system_installation_guard
BEFORE UPDATE OR DELETE ON system_installation
FOR EACH ROW EXECUTE FUNCTION guard_system_installation();

-- Retained legacy-facing fields keep their integer wire representation. Named
-- CHECK constraints enforce the native domain without forcing an API or import
-- type translation to PostgreSQL BOOLEAN.
CREATE TABLE server_group (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE plan (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INTEGER NOT NULL,
    transfer_enable BIGINT NOT NULL,
    device_limit INTEGER,
    name VARCHAR(255) NOT NULL,
    speed_limit INTEGER,
    show SMALLINT NOT NULL DEFAULT 0,
    sort INTEGER,
    renew SMALLINT NOT NULL DEFAULT 1,
    content TEXT,
    month_price INTEGER,
    quarter_price INTEGER,
    half_year_price INTEGER,
    year_price INTEGER,
    two_year_price INTEGER,
    three_year_price INTEGER,
    onetime_price INTEGER,
    reset_price INTEGER,
    reset_traffic_method SMALLINT,
    capacity_limit INTEGER,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT chk_plan_flags CHECK (show IN (0, 1) AND renew IN (0, 1)),
    CONSTRAINT chk_plan_transfer_nonnegative CHECK (transfer_enable >= 0),
    CONSTRAINT chk_plan_reset_traffic_method CHECK (
        reset_traffic_method IS NULL OR reset_traffic_method BETWEEN 0 AND 4
    )
);

CREATE TABLE payment_method (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(32) NOT NULL,
    payment VARCHAR(16) NOT NULL,
    name VARCHAR(255) NOT NULL,
    icon VARCHAR(255),
    config JSONB NOT NULL,
    notify_domain VARCHAR(128),
    handling_fee_fixed INTEGER,
    handling_fee_percent NUMERIC(5,2),
    enable SMALLINT NOT NULL DEFAULT 0,
    archived_at BIGINT,
    sort INTEGER,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT chk_payment_method_enable CHECK (enable IN (0, 1))
);

CREATE TABLE coupon (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    type SMALLINT NOT NULL,
    value INTEGER NOT NULL,
    show SMALLINT NOT NULL DEFAULT 0,
    limit_use INTEGER,
    limit_use_with_user INTEGER,
    limit_plan_ids JSONB,
    limit_period JSONB,
    started_at BIGINT NOT NULL,
    ended_at BIGINT NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT chk_coupon_type_value CHECK (
        (type = 1 AND value >= 0)
        OR (type = 2 AND value BETWEEN 0 AND 100)
    ),
    CONSTRAINT chk_coupon_show CHECK (show IN (0, 1)),
    CONSTRAINT chk_coupon_limit_plan_ids_array
        CHECK (limit_plan_ids IS NULL OR jsonb_typeof(limit_plan_ids) = 'array'),
    CONSTRAINT chk_coupon_limit_period_array
        CHECK (limit_period IS NULL OR jsonb_typeof(limit_period) = 'array')
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invite_user_id BIGINT,
    telegram_id BIGINT,
    email VARCHAR(64) NOT NULL,
    password VARCHAR(255) NOT NULL,
    password_algo VARCHAR(10),
    password_salt VARCHAR(10),
    session_epoch BIGINT NOT NULL DEFAULT 0,
    traffic_epoch BIGINT NOT NULL DEFAULT 0,
    scheduled_traffic_reset_key VARCHAR(10),
    balance INTEGER NOT NULL DEFAULT 0,
    discount INTEGER,
    commission_type SMALLINT NOT NULL DEFAULT 0,
    commission_rate INTEGER,
    commission_balance INTEGER NOT NULL DEFAULT 0,
    t BIGINT NOT NULL DEFAULT 0,
    u BIGINT NOT NULL DEFAULT 0,
    d BIGINT NOT NULL DEFAULT 0,
    transfer_enable BIGINT NOT NULL DEFAULT 0,
    device_limit INTEGER,
    banned SMALLINT NOT NULL DEFAULT 0,
    is_admin SMALLINT NOT NULL DEFAULT 0,
    last_login_at BIGINT,
    is_staff SMALLINT NOT NULL DEFAULT 0,
    last_login_ip INTEGER,
    uuid VARCHAR(36) NOT NULL,
    group_id INTEGER,
    plan_id INTEGER,
    speed_limit INTEGER,
    auto_renewal SMALLINT DEFAULT 0,
    remind_expire SMALLINT DEFAULT 1,
    remind_traffic SMALLINT DEFAULT 1,
    token VARCHAR(32) NOT NULL,
    expired_at BIGINT DEFAULT 0,
    remarks TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT chk_user_epochs_nonnegative CHECK (
        session_epoch >= 0 AND traffic_epoch >= 0
    ),
    CONSTRAINT chk_user_traffic_nonnegative CHECK (
        t >= 0 AND u >= 0 AND d >= 0 AND transfer_enable >= 0
    ),
    CONSTRAINT chk_user_role_flags CHECK (
        banned IN (0, 1) AND is_admin IN (0, 1) AND is_staff IN (0, 1)
    ),
    CONSTRAINT chk_user_preference_flags CHECK (
        auto_renewal IS NULL OR auto_renewal IN (0, 1)
    ),
    CONSTRAINT chk_user_reminder_flags CHECK (
        (remind_expire IS NULL OR remind_expire IN (0, 1))
        AND (remind_traffic IS NULL OR remind_traffic IN (0, 1))
    )
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invite_user_id BIGINT,
    user_id BIGINT NOT NULL,
    plan_id INTEGER NOT NULL,
    referenced_plan_id INTEGER GENERATED ALWAYS AS (NULLIF(plan_id, 0)) STORED,
    coupon_id INTEGER,
    payment_id INTEGER,
    type INTEGER NOT NULL,
    period VARCHAR(255) NOT NULL,
    trade_no VARCHAR(36) NOT NULL,
    callback_no VARCHAR(255),
    callback_no_hash BYTEA,
    total_amount INTEGER NOT NULL,
    handling_amount INTEGER,
    discount_amount INTEGER,
    surplus_amount INTEGER,
    refund_amount INTEGER,
    balance_amount INTEGER,
    surplus_order_ids TEXT,
    status SMALLINT NOT NULL DEFAULT 0,
    commission_status SMALLINT NOT NULL DEFAULT 0,
    commission_balance INTEGER NOT NULL DEFAULT 0,
    actual_commission_balance INTEGER,
    paid_at BIGINT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT chk_order_type CHECK (type IN (1, 2, 3, 4, 9)),
    CONSTRAINT chk_order_status CHECK (status BETWEEN 0 AND 4),
    CONSTRAINT chk_order_commission_status CHECK (commission_status BETWEEN 0 AND 3),
    CONSTRAINT chk_order_amounts_nonnegative CHECK (
        total_amount >= 0
        AND (handling_amount IS NULL OR handling_amount >= 0)
        AND (discount_amount IS NULL OR discount_amount >= 0)
        AND (surplus_amount IS NULL OR surplus_amount >= 0)
        AND (refund_amount IS NULL OR refund_amount >= 0)
        AND (balance_amount IS NULL OR balance_amount >= 0)
        AND commission_balance >= 0
        AND (actual_commission_balance IS NULL OR actual_commission_balance >= 0)
    ),
    CONSTRAINT chk_order_callback_hash_size
        CHECK (callback_no_hash IS NULL OR octet_length(callback_no_hash) = 32)
);

CREATE TABLE commission_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invite_user_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    trade_no VARCHAR(36) NOT NULL,
    order_amount INTEGER NOT NULL,
    get_amount INTEGER NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT chk_commission_log_amounts_nonnegative CHECK (
        order_amount >= 0 AND get_amount >= 0
    )
);

CREATE TABLE invite_code (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    code VARCHAR(32) NOT NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    pv INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT chk_invite_code_status CHECK (status IN (0, 1)),
    CONSTRAINT chk_invite_code_pv_nonnegative CHECK (pv >= 0)
);

CREATE TABLE gift_card (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    type SMALLINT NOT NULL,
    value INTEGER,
    plan_id INTEGER,
    limit_use INTEGER,
    started_at BIGINT NOT NULL,
    ended_at BIGINT NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT chk_gift_card_type_value CHECK (
        type = 4
        OR (type IN (1, 2, 3, 5) AND value IS NOT NULL AND value >= 0)
    ),
    CONSTRAINT chk_gift_card_plan CHECK (type <> 5 OR plan_id IS NOT NULL)
);

CREATE TABLE gift_card_redemption (
    giftcard_id INTEGER NOT NULL,
    user_id BIGINT NOT NULL,
    created_at BIGINT NOT NULL,
    created_at_provenance TEXT NOT NULL DEFAULT 'native'
        CHECK (created_at_provenance IN ('native', 'legacy_unknown')),
    CONSTRAINT chk_gift_card_redemption_created_at_provenance CHECK (
        (created_at_provenance = 'native' AND created_at > 0)
        OR (created_at_provenance = 'legacy_unknown' AND created_at = 0)
    ),
    PRIMARY KEY (giftcard_id, user_id)
);

CREATE TABLE payment_reconciliation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id INTEGER NOT NULL REFERENCES payment_method(id) ON DELETE RESTRICT,
    provider VARCHAR(32) NOT NULL,
    trade_no VARCHAR(255) NOT NULL,
    trade_no_hash BYTEA NOT NULL CHECK (octet_length(trade_no_hash) = 32),
    callback_no VARCHAR(255) NOT NULL,
    callback_no_hash BYTEA NOT NULL CHECK (octet_length(callback_no_hash) = 32),
    reason VARCHAR(64) NOT NULL,
    order_status SMALLINT NOT NULL,
    expected_amount BIGINT NOT NULL CHECK (expected_amount >= 0),
    settled_amount BIGINT CHECK (settled_amount IS NULL OR settled_amount >= 0),
    occurrence_count INTEGER NOT NULL DEFAULT 1 CHECK (occurrence_count > 0),
    first_seen_at BIGINT NOT NULL,
    last_seen_at BIGINT NOT NULL,
    resolved_at BIGINT,
    resolution VARCHAR(255),
    CONSTRAINT uniq_payment_reconciliation_callback
        UNIQUE (payment_id, callback_no_hash)
);
CREATE INDEX idx_payment_reconciliation_open
    ON payment_reconciliation(resolved_at, first_seen_at);
CREATE INDEX idx_payment_reconciliation_trade
    ON payment_reconciliation(trade_no_hash);

CREATE TABLE knowledge (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language VARCHAR(5) NOT NULL,
    category VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    sort INTEGER,
    show SMALLINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT chk_knowledge_show CHECK (show IN (0, 1))
);

CREATE TABLE notice (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    show SMALLINT NOT NULL DEFAULT 0,
    img_url VARCHAR(255),
    tags JSONB CHECK (tags IS NULL OR jsonb_typeof(tags) = 'array'),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT chk_notice_show CHECK (show IN (0, 1))
);

CREATE TABLE ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    subject VARCHAR(255) NOT NULL,
    level SMALLINT NOT NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    reply_status SMALLINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT chk_ticket_level CHECK (level BETWEEN 0 AND 2),
    CONSTRAINT chk_ticket_status CHECK (status IN (0, 1)),
    CONSTRAINT chk_ticket_reply_status CHECK (reply_status IN (0, 1))
);

CREATE TABLE ticket_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    ticket_id BIGINT NOT NULL,
    message TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE system_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    level VARCHAR(11),
    host VARCHAR(255),
    uri VARCHAR(255) NOT NULL,
    method VARCHAR(11) NOT NULL,
    data TEXT,
    ip VARCHAR(128),
    context TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);
CREATE INDEX idx_system_log_created_at ON system_log(created_at);

CREATE TABLE mail_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(512) NOT NULL,
    subject TEXT NOT NULL,
    template_name VARCHAR(255) NOT NULL,
    error TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);
CREATE INDEX idx_mail_log_created_at ON mail_log(created_at, id);

CREATE TABLE mail_outbox_batch (
    batch_key VARCHAR(64) PRIMARY KEY,
    payload_hash VARCHAR(64) NOT NULL,
    actor VARCHAR(512) NOT NULL,
    sender VARCHAR(512),
    template_name VARCHAR(255),
    subject TEXT,
    body TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE mail_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_key VARCHAR(64) NOT NULL REFERENCES mail_outbox_batch(batch_key) ON DELETE CASCADE,
    recipient VARCHAR(512) NOT NULL,
    message_id VARCHAR(255) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    available_at BIGINT NOT NULL,
    lease_token VARCHAR(36),
    lease_expires_at BIGINT,
    failed_at BIGINT,
    last_error TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT uniq_mail_outbox_batch_recipient UNIQUE (batch_key, recipient),
    CONSTRAINT uniq_mail_outbox_message_id UNIQUE (message_id)
);
CREATE INDEX idx_mail_outbox_claim ON mail_outbox(failed_at, available_at, id);
CREATE INDEX idx_mail_outbox_lease ON mail_outbox(lease_expires_at);

CREATE TABLE stat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_at BIGINT NOT NULL,
    record_type VARCHAR(1) NOT NULL,
    order_count INTEGER NOT NULL,
    order_total BIGINT NOT NULL,
    commission_count INTEGER NOT NULL,
    commission_total BIGINT NOT NULL,
    paid_count INTEGER NOT NULL,
    paid_total BIGINT NOT NULL,
    register_count INTEGER NOT NULL,
    invite_count INTEGER NOT NULL,
    transfer_used_total VARCHAR(32) NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT chk_stat_counts_nonnegative CHECK (
        order_count >= 0
        AND commission_count >= 0
        AND paid_count >= 0
        AND register_count >= 0
        AND invite_count >= 0
    ),
    CONSTRAINT chk_stat_amounts_nonnegative CHECK (
        order_total >= 0 AND commission_total >= 0 AND paid_total >= 0
    )
);

CREATE TABLE server_traffic (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_id INTEGER NOT NULL,
    server_type VARCHAR(11) NOT NULL,
    u BIGINT NOT NULL,
    d BIGINT NOT NULL,
    record_type VARCHAR(1) NOT NULL,
    record_at BIGINT NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT uniq_server_traffic_day UNIQUE (server_id, server_type, record_at),
    CONSTRAINT chk_server_traffic_nonnegative CHECK (u >= 0 AND d >= 0)
);
CREATE INDEX idx_server_traffic_record_at ON server_traffic(record_at);
CREATE INDEX idx_server_traffic_server_id ON server_traffic(server_id);

CREATE TABLE user_traffic (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    server_rate NUMERIC(10,2) NOT NULL,
    u BIGINT NOT NULL,
    d BIGINT NOT NULL,
    record_type VARCHAR(2) NOT NULL,
    record_at BIGINT NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT uniq_user_traffic_day UNIQUE (server_rate, user_id, record_at),
    CONSTRAINT chk_user_traffic_history_nonnegative CHECK (
        server_rate >= 0 AND u >= 0 AND d >= 0
    )
);
CREATE INDEX idx_user_traffic_record_at ON user_traffic(record_at);
CREATE INDEX idx_user_traffic_user_record_at ON user_traffic(user_id, record_at DESC);

CREATE TABLE analytics_delivery_batch (
    batch_id UUID PRIMARY KEY,
    event_name TEXT NOT NULL CHECK (btrim(event_name) <> ''),
    schema_major SMALLINT NOT NULL CHECK (schema_major > 0),
    partition_month DATE NOT NULL CHECK (
        partition_month = date_trunc('month', partition_month)::date
    ),
    row_count INTEGER NOT NULL CHECK (row_count BETWEEN 1 AND 100000),
    content_sha256 TEXT NOT NULL CHECK (content_sha256 ~ '^[0-9a-f]{64}$'),
    insert_settings_sha256 TEXT NOT NULL CHECK (insert_settings_sha256 ~ '^[0-9a-f]{64}$'),
    state TEXT NOT NULL CHECK (state IN ('ready', 'publishing', 'published', 'quarantined')),
    lease_owner UUID,
    lease_expires_at BIGINT,
    attempt_count INTEGER NOT NULL CHECK (attempt_count > 0),
    published_at BIGINT,
    quarantined_at BIGINT,
    quarantine_reason TEXT,
    last_error TEXT,
    created_at BIGINT NOT NULL,
    CONSTRAINT chk_analytics_batch_state CHECK (
        (state = 'ready'
            AND lease_owner IS NULL AND lease_expires_at IS NULL
            AND published_at IS NULL AND quarantined_at IS NULL)
        OR (state = 'publishing'
            AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL
            AND published_at IS NULL AND quarantined_at IS NULL)
        OR (state = 'published'
            AND lease_owner IS NULL AND lease_expires_at IS NULL
            AND published_at IS NOT NULL AND quarantined_at IS NULL)
        OR (state = 'quarantined'
            AND lease_owner IS NULL AND lease_expires_at IS NULL
            AND published_at IS NULL AND quarantined_at IS NOT NULL
            AND quarantine_reason IS NOT NULL)
    ),
    CONSTRAINT chk_analytics_batch_terminal_time CHECK (
        published_at IS NULL OR quarantined_at IS NULL
    )
);
CREATE INDEX idx_analytics_batch_claim
    ON analytics_delivery_batch(created_at, batch_id)
    WHERE published_at IS NULL AND quarantined_at IS NULL
      AND state IN ('ready', 'publishing');
CREATE INDEX idx_analytics_batch_lease
    ON analytics_delivery_batch(lease_expires_at, created_at, batch_id)
    WHERE state = 'publishing' AND published_at IS NULL AND quarantined_at IS NULL;
CREATE INDEX idx_analytics_batch_published_cleanup
    ON analytics_delivery_batch(published_at, batch_id)
    WHERE state = 'published' AND published_at IS NOT NULL;

CREATE TABLE analytics_outbox (
    outbox_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL,
    event_name TEXT NOT NULL CHECK (btrim(event_name) <> ''),
    schema_major SMALLINT NOT NULL CHECK (schema_major > 0),
    report_key VARCHAR(64) NOT NULL CHECK (report_key <> ''),
    partition_month DATE NOT NULL CHECK (
        partition_month = date_trunc('month', partition_month)::date
    ),
    occurred_at BIGINT NOT NULL,
    payload JSONB NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
    payload_sha256 TEXT NOT NULL CHECK (payload_sha256 ~ '^[0-9a-f]{64}$'),
    delivery_batch_id UUID REFERENCES analytics_delivery_batch(batch_id) ON DELETE RESTRICT,
    batch_row_number INTEGER,
    published_at BIGINT,
    quarantined_at BIGINT,
    created_at BIGINT NOT NULL,
    CONSTRAINT uniq_analytics_event_id UNIQUE (event_id),
    CONSTRAINT uniq_analytics_batch_row UNIQUE (delivery_batch_id, batch_row_number),
    CONSTRAINT chk_analytics_event_id CHECK (event_id ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_analytics_batch_assignment CHECK (
        (delivery_batch_id IS NULL AND batch_row_number IS NULL)
        OR (delivery_batch_id IS NOT NULL
            AND batch_row_number IS NOT NULL
            AND batch_row_number >= 0)
    ),
    CONSTRAINT chk_analytics_outbox_terminal CHECK (
        (published_at IS NULL OR quarantined_at IS NULL)
        AND ((published_at IS NULL AND quarantined_at IS NULL) OR delivery_batch_id IS NOT NULL)
    )
);
CREATE INDEX idx_analytics_outbox_unpublished
    ON analytics_outbox(outbox_id)
    WHERE published_at IS NULL AND quarantined_at IS NULL;
CREATE INDEX idx_analytics_outbox_backlog
    ON analytics_outbox(created_at, outbox_id)
    WHERE published_at IS NULL AND quarantined_at IS NULL;
CREATE INDEX idx_analytics_outbox_published_cleanup
    ON analytics_outbox(published_at, outbox_id)
    WHERE published_at IS NOT NULL AND quarantined_at IS NULL;
CREATE INDEX idx_analytics_outbox_unbatched_claim
    ON analytics_outbox(event_name, schema_major, partition_month, outbox_id)
    WHERE published_at IS NULL AND quarantined_at IS NULL AND delivery_batch_id IS NULL;

CREATE TABLE server_traffic_report (
    report_key VARCHAR(64) PRIMARY KEY,
    payload_hash VARCHAR(64) NOT NULL CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    node_id INTEGER NOT NULL CHECK (node_id > 0),
    node_type VARCHAR(32) NOT NULL CHECK (node_type <> ''),
    rate_text TEXT NOT NULL CHECK (btrim(rate_text) <> ''),
    rate_decimal_10_2 NUMERIC(10,2) NOT NULL CHECK (rate_decimal_10_2 >= 0),
    identity_kind TEXT NOT NULL CHECK (identity_kind IN ('explicit', 'implicit')),
    accepted_at BIGINT NOT NULL,
    accounting_date DATE NOT NULL,
    applied_at BIGINT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT chk_traffic_report_applied_after_acceptance CHECK (
        applied_at IS NULL OR applied_at >= accepted_at
    )
);
CREATE INDEX idx_traffic_report_claim
    ON server_traffic_report(created_at, report_key)
    WHERE applied_at IS NULL;
CREATE INDEX idx_traffic_report_retention
    ON server_traffic_report(applied_at, report_key)
    WHERE applied_at IS NOT NULL;

CREATE TABLE server_traffic_report_item (
    report_key VARCHAR(64) NOT NULL
        REFERENCES server_traffic_report(report_key) ON DELETE CASCADE,
    -- Deliberately not an FK: the API proves authorization while accepting the
    -- report, then a concurrent administrative user deletion is represented by
    -- the worker's durable `missing_user` accounting outcome instead of making
    -- user deletion depend on relay timing.
    user_id BIGINT NOT NULL,
    traffic_epoch BIGINT NOT NULL DEFAULT 0,
    raw_u BIGINT NOT NULL CHECK (raw_u >= 0),
    raw_d BIGINT NOT NULL CHECK (raw_d >= 0),
    charged_u BIGINT NOT NULL CHECK (charged_u >= 0),
    charged_d BIGINT NOT NULL CHECK (charged_d >= 0),
    PRIMARY KEY (report_key, user_id)
);
CREATE INDEX idx_traffic_report_item_user ON server_traffic_report_item(user_id);

CREATE TABLE server_credential (
    node_type VARCHAR(32) NOT NULL,
    node_id INTEGER NOT NULL,
    credential_epoch BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (node_type, node_id)
);

CREATE TABLE server_route (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remarks VARCHAR(255) NOT NULL,
    match JSONB NOT NULL,
    action VARCHAR(11) NOT NULL,
    action_value JSONB,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE server_shadowsocks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id JSONB NOT NULL CHECK (jsonb_typeof(group_id) = 'array' AND jsonb_array_length(group_id) > 0),
    route_id JSONB,
    parent_id INTEGER,
    tags JSONB,
    name VARCHAR(255) NOT NULL,
    rate VARCHAR(11) NOT NULL,
    host VARCHAR(255) NOT NULL,
    port VARCHAR(11) NOT NULL,
    server_port INTEGER NOT NULL,
    cipher VARCHAR(255) NOT NULL,
    obfs VARCHAR(11),
    obfs_settings JSONB,
    show SMALLINT NOT NULL DEFAULT 0,
    sort INTEGER,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE server_vmess (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id JSONB NOT NULL CHECK (jsonb_typeof(group_id) = 'array' AND jsonb_array_length(group_id) > 0),
    route_id JSONB,
    name VARCHAR(255) NOT NULL,
    parent_id INTEGER,
    host VARCHAR(255) NOT NULL,
    port VARCHAR(11) NOT NULL,
    server_port INTEGER NOT NULL,
    tls SMALLINT NOT NULL DEFAULT 0,
    tags JSONB,
    rate VARCHAR(11) NOT NULL,
    network VARCHAR(11) NOT NULL,
    rules JSONB,
    "networkSettings" JSONB,
    "tlsSettings" JSONB,
    "ruleSettings" JSONB,
    "dnsSettings" JSONB,
    show SMALLINT NOT NULL DEFAULT 0,
    sort INTEGER,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE server_trojan (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id JSONB NOT NULL CHECK (jsonb_typeof(group_id) = 'array' AND jsonb_array_length(group_id) > 0),
    route_id JSONB,
    parent_id INTEGER,
    tags JSONB,
    name VARCHAR(255) NOT NULL,
    rate VARCHAR(11) NOT NULL,
    host VARCHAR(255) NOT NULL,
    port VARCHAR(11) NOT NULL,
    server_port INTEGER NOT NULL,
    network VARCHAR(11),
    network_settings JSONB,
    allow_insecure SMALLINT NOT NULL DEFAULT 0,
    server_name VARCHAR(255),
    show SMALLINT NOT NULL DEFAULT 0,
    sort INTEGER,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE server_tuic (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id JSONB NOT NULL CHECK (jsonb_typeof(group_id) = 'array' AND jsonb_array_length(group_id) > 0),
    route_id JSONB,
    name VARCHAR(255) NOT NULL,
    parent_id INTEGER,
    host VARCHAR(255) NOT NULL,
    port VARCHAR(11) NOT NULL,
    server_port INTEGER NOT NULL,
    tags JSONB,
    rate VARCHAR(11) NOT NULL,
    show SMALLINT NOT NULL DEFAULT 0,
    sort INTEGER,
    server_name VARCHAR(64),
    insecure SMALLINT NOT NULL DEFAULT 0,
    disable_sni SMALLINT NOT NULL DEFAULT 0,
    udp_relay_mode VARCHAR(64),
    zero_rtt_handshake SMALLINT NOT NULL DEFAULT 0,
    congestion_control VARCHAR(64),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE server_hysteria (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL,
    group_id JSONB NOT NULL CHECK (jsonb_typeof(group_id) = 'array' AND jsonb_array_length(group_id) > 0),
    route_id JSONB,
    name VARCHAR(255) NOT NULL,
    parent_id INTEGER,
    host VARCHAR(255) NOT NULL,
    port VARCHAR(11) NOT NULL,
    server_port INTEGER NOT NULL,
    tags JSONB,
    rate VARCHAR(11) NOT NULL,
    show SMALLINT NOT NULL DEFAULT 0,
    sort INTEGER,
    up_mbps INTEGER NOT NULL,
    down_mbps INTEGER NOT NULL,
    obfs VARCHAR(64),
    obfs_password VARCHAR(255),
    server_name VARCHAR(64),
    insecure SMALLINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE server_vless (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id JSONB NOT NULL CHECK (jsonb_typeof(group_id) = 'array' AND jsonb_array_length(group_id) > 0),
    route_id JSONB,
    name VARCHAR(255) NOT NULL,
    parent_id INTEGER,
    host VARCHAR(255) NOT NULL,
    port INTEGER NOT NULL,
    server_port INTEGER NOT NULL,
    tls SMALLINT NOT NULL,
    tls_settings JSONB,
    flow VARCHAR(64),
    network VARCHAR(11) NOT NULL,
    network_settings JSONB,
    encryption VARCHAR(64),
    encryption_settings JSONB,
    tags JSONB,
    rate VARCHAR(11) NOT NULL,
    show SMALLINT NOT NULL DEFAULT 0,
    sort INTEGER,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE server_anytls (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id JSONB NOT NULL CHECK (jsonb_typeof(group_id) = 'array' AND jsonb_array_length(group_id) > 0),
    route_id JSONB,
    name VARCHAR(255) NOT NULL,
    parent_id INTEGER,
    host VARCHAR(255) NOT NULL,
    port VARCHAR(11) NOT NULL,
    server_port INTEGER NOT NULL,
    tags JSONB,
    rate VARCHAR(11) NOT NULL,
    show SMALLINT NOT NULL DEFAULT 0,
    sort INTEGER,
    server_name VARCHAR(64),
    insecure SMALLINT NOT NULL DEFAULT 0,
    padding_scheme JSONB,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE server_v2node (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id JSONB NOT NULL CHECK (jsonb_typeof(group_id) = 'array' AND jsonb_array_length(group_id) > 0),
    route_id JSONB,
    name VARCHAR(255) NOT NULL,
    parent_id INTEGER,
    host VARCHAR(255) NOT NULL,
    listen_ip VARCHAR(255) NOT NULL DEFAULT '0.0.0.0',
    port VARCHAR(11) NOT NULL,
    server_port INTEGER NOT NULL,
    tags JSONB,
    rate VARCHAR(11) NOT NULL,
    show SMALLINT NOT NULL DEFAULT 0,
    sort INTEGER,
    protocol VARCHAR(24) NOT NULL,
    tls SMALLINT NOT NULL,
    tls_settings JSONB,
    flow VARCHAR(64),
    network VARCHAR(11) NOT NULL,
    network_settings JSONB,
    encryption VARCHAR(64),
    encryption_settings JSONB,
    disable_sni SMALLINT NOT NULL DEFAULT 0,
    udp_relay_mode VARCHAR(64),
    zero_rtt_handshake SMALLINT NOT NULL DEFAULT 0,
    congestion_control VARCHAR(64),
    cipher VARCHAR(64),
    up_mbps INTEGER NOT NULL,
    down_mbps INTEGER NOT NULL,
    obfs VARCHAR(64),
    obfs_password VARCHAR(255),
    padding_scheme JSONB,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

-- Machine-bound analytics admission policy. Runtime principals may read this
-- row but cannot alter it; import/install tooling supplies the policy for the
-- installation identity.
CREATE TABLE analytics_admission_policy (
    singleton SMALLINT PRIMARY KEY CHECK (singleton = 1),
    installation_id UUID NOT NULL UNIQUE
        REFERENCES system_installation(installation_id) ON DELETE RESTRICT,
    policy_sha256 TEXT NOT NULL UNIQUE CHECK (policy_sha256 ~ '^[0-9a-f]{64}$'),
    recovery_pending_rows BIGINT NOT NULL CHECK (recovery_pending_rows >= 0),
    soft_pending_rows BIGINT NOT NULL CHECK (soft_pending_rows > recovery_pending_rows),
    hard_pending_rows BIGINT NOT NULL CHECK (hard_pending_rows > soft_pending_rows),
    recovery_relation_bytes BIGINT NOT NULL CHECK (recovery_relation_bytes >= 0),
    soft_relation_bytes BIGINT NOT NULL CHECK (soft_relation_bytes > recovery_relation_bytes),
    hard_relation_bytes BIGINT NOT NULL CHECK (hard_relation_bytes > soft_relation_bytes),
    recovery_oldest_age_seconds BIGINT NOT NULL CHECK (recovery_oldest_age_seconds >= 0),
    soft_oldest_age_seconds BIGINT NOT NULL CHECK (soft_oldest_age_seconds > recovery_oldest_age_seconds),
    hard_oldest_age_seconds BIGINT NOT NULL CHECK (hard_oldest_age_seconds > soft_oldest_age_seconds),
    database_capacity_bytes BIGINT NOT NULL CHECK (database_capacity_bytes > 0),
    hard_min_headroom_bytes BIGINT NOT NULL CHECK (hard_min_headroom_bytes >= 0),
    soft_min_headroom_bytes BIGINT NOT NULL CHECK (soft_min_headroom_bytes > hard_min_headroom_bytes),
    recovery_min_headroom_bytes BIGINT NOT NULL CHECK (recovery_min_headroom_bytes > soft_min_headroom_bytes),
    event_reservation_bytes BIGINT NOT NULL CHECK (event_reservation_bytes > 0),
    soft_max_new_rows_per_second BIGINT NOT NULL CHECK (
        soft_max_new_rows_per_second BETWEEN 100000 AND 10000000
    ),
    sample_interval_seconds BIGINT NOT NULL CHECK (sample_interval_seconds BETWEEN 1 AND 60),
    stale_after_seconds BIGINT NOT NULL CHECK (
        stale_after_seconds BETWEEN sample_interval_seconds * 2 AND 600
    ),
    capacity_evidence TEXT NOT NULL CHECK (length(btrim(capacity_evidence)) BETWEEN 8 AND 1024),
    installed_at BIGINT NOT NULL CHECK (installed_at > 0),
    CONSTRAINT chk_analytics_admission_capacity_order CHECK (
        database_capacity_bytes > recovery_min_headroom_bytes
    )
);

CREATE FUNCTION guard_analytics_admission_policy()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'analytics admission policy is immutable';
END;
$$;

CREATE TRIGGER trg_analytics_admission_policy_immutable
BEFORE UPDATE OR DELETE ON analytics_admission_policy
FOR EACH ROW EXECUTE FUNCTION guard_analytics_admission_policy();

-- This singleton is the cheap hot-path admission state. The worker refreshes
-- exact PostgreSQL measurements; every producer serializes reservations here
-- in the same transaction as its business mutation and outbox insert.
CREATE TABLE analytics_admission_state (
    singleton SMALLINT PRIMARY KEY CHECK (singleton = 1),
    installation_id UUID NOT NULL UNIQUE
        REFERENCES analytics_admission_policy(installation_id) ON DELETE RESTRICT,
    pressure_state TEXT NOT NULL CHECK (pressure_state IN ('normal', 'soft_pressure', 'hard_stop')),
    generation BIGINT NOT NULL CHECK (generation >= 0),
    sampled_at BIGINT NOT NULL CHECK (sampled_at > 0),
    state_changed_at BIGINT NOT NULL CHECK (state_changed_at > 0),
    pending_rows BIGINT NOT NULL CHECK (pending_rows >= 0),
    oldest_pending_created_at BIGINT,
    relation_heap_bytes BIGINT NOT NULL CHECK (relation_heap_bytes >= 0),
    relation_index_bytes BIGINT NOT NULL CHECK (relation_index_bytes >= 0),
    relation_toast_bytes BIGINT NOT NULL CHECK (relation_toast_bytes >= 0),
    relation_total_bytes BIGINT NOT NULL CHECK (relation_total_bytes >= 0),
    database_bytes BIGINT NOT NULL CHECK (database_bytes >= 0),
    capacity_headroom_bytes BIGINT NOT NULL,
    accounted_pending_rows BIGINT NOT NULL CHECK (accounted_pending_rows >= 0),
    accounted_relation_bytes BIGINT NOT NULL CHECK (accounted_relation_bytes >= 0),
    soft_window_started_at BIGINT NOT NULL CHECK (soft_window_started_at > 0),
    soft_window_admitted_rows BIGINT NOT NULL CHECK (soft_window_admitted_rows >= 0),
    last_transition_reason TEXT NOT NULL CHECK (length(last_transition_reason) BETWEEN 1 AND 128),
    CONSTRAINT chk_analytics_admission_relation_parts CHECK (
        relation_total_bytes >= relation_heap_bytes + relation_index_bytes
        AND relation_toast_bytes = relation_total_bytes - relation_heap_bytes - relation_index_bytes
    )
);

CREATE FUNCTION guard_analytics_admission_state()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'analytics admission state cannot be deleted';
    END IF;
    IF NEW.singleton IS DISTINCT FROM OLD.singleton
       OR NEW.installation_id IS DISTINCT FROM OLD.installation_id THEN
        RAISE EXCEPTION 'analytics admission state identity cannot change';
    END IF;
    IF NEW.generation <> OLD.generation + 1 THEN
        RAISE EXCEPTION 'analytics admission generation must advance exactly once';
    END IF;
    IF NEW.sampled_at < OLD.sampled_at OR NEW.state_changed_at < OLD.state_changed_at THEN
        RAISE EXCEPTION 'analytics admission timestamps cannot regress';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_analytics_admission_state_guard
BEFORE UPDATE OR DELETE ON analytics_admission_state
FOR EACH ROW EXECUTE FUNCTION guard_analytics_admission_state();

-- Runtime role files remain the bootstrap source for datastore credentials and
-- the application key. Mutable operator settings are committed here once and
-- consumed by both the API and worker. Revision rows are immutable; the
-- singleton state pointer selects the current revision.
CREATE TABLE operator_config_revision (
    revision BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    revision_id UUID NOT NULL UNIQUE,
    format_version SMALLINT NOT NULL,
    installation_id UUID NOT NULL,
    public_config JSONB NOT NULL,
    secret_nonce BYTEA NOT NULL,
    secret_ciphertext BYTEA NOT NULL,
    secret_tag BYTEA NOT NULL,
    config_hmac_sha256 VARCHAR(64) NOT NULL,
    created_by VARCHAR(64) NOT NULL,
    created_at BIGINT NOT NULL,
    CONSTRAINT fk_operator_config_revision_installation
        FOREIGN KEY (installation_id)
        REFERENCES system_installation(installation_id) ON DELETE RESTRICT,
    CONSTRAINT uniq_operator_config_revision_installation
        UNIQUE (revision, installation_id),
    CONSTRAINT chk_operator_config_public_object
        CHECK (jsonb_typeof(public_config) = 'object'),
    CONSTRAINT chk_operator_config_format_version
        CHECK (format_version = 1),
    CONSTRAINT chk_operator_config_public_has_no_secrets
        CHECK (NOT (public_config ?| ARRAY[
            'server_token',
            'email_password',
            'telegram_bot_token',
            'recaptcha_key'
        ])),
    CONSTRAINT chk_operator_config_nonce_length
        CHECK (octet_length(secret_nonce) = 12),
    CONSTRAINT chk_operator_config_ciphertext_present
        CHECK (octet_length(secret_ciphertext) > 0),
    CONSTRAINT chk_operator_config_tag_length
        CHECK (octet_length(secret_tag) = 16),
    CONSTRAINT chk_operator_config_hmac
        CHECK (config_hmac_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_operator_config_actor_present
        CHECK (length(btrim(created_by)) > 0)
);

CREATE FUNCTION guard_operator_config_revision()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'operator configuration revisions are immutable';
END;
$$;

CREATE TRIGGER trg_operator_config_revision_immutable
BEFORE UPDATE OR DELETE ON operator_config_revision
FOR EACH ROW EXECUTE FUNCTION guard_operator_config_revision();

CREATE TABLE operator_config_state (
    singleton SMALLINT PRIMARY KEY CHECK (singleton = 1),
    installation_id UUID NOT NULL,
    active_revision BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT fk_operator_config_state_revision
        FOREIGN KEY (active_revision, installation_id)
        REFERENCES operator_config_revision(revision, installation_id)
        ON DELETE RESTRICT
);

CREATE FUNCTION guard_operator_config_state()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'operator configuration state cannot be deleted';
    END IF;
    IF NEW.singleton IS DISTINCT FROM OLD.singleton
       OR NEW.installation_id IS DISTINCT FROM OLD.installation_id THEN
        RAISE EXCEPTION 'operator configuration state identity cannot change';
    END IF;
    IF NEW.active_revision < OLD.active_revision THEN
        RAISE EXCEPTION 'operator configuration revision cannot move backwards';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_operator_config_state_guard
BEFORE UPDATE OR DELETE ON operator_config_state
FOR EACH ROW EXECUTE FUNCTION guard_operator_config_state();

CREATE FUNCTION guard_operator_config_ack()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'operator configuration acknowledgement cannot be deleted';
    END IF;
    IF NEW.singleton IS DISTINCT FROM OLD.singleton
       OR NEW.installation_id IS DISTINCT FROM OLD.installation_id THEN
        RAISE EXCEPTION 'operator configuration acknowledgement identity cannot change';
    END IF;
    IF NEW.observed_revision < OLD.observed_revision
       OR COALESCE(NEW.applied_revision, 0) < COALESCE(OLD.applied_revision, 0) THEN
        RAISE EXCEPTION 'operator configuration acknowledgement cannot move backwards';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TABLE operator_config_api_ack (
    singleton SMALLINT PRIMARY KEY CHECK (singleton = 1),
    installation_id UUID NOT NULL,
    observed_revision BIGINT NOT NULL,
    applied_revision BIGINT,
    status VARCHAR(16) NOT NULL CHECK (status IN ('applied', 'rejected')),
    error_code VARCHAR(64),
    observed_at BIGINT NOT NULL,
    CONSTRAINT fk_operator_config_api_ack_observed
        FOREIGN KEY (observed_revision, installation_id)
        REFERENCES operator_config_revision(revision, installation_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_operator_config_api_ack_applied
        FOREIGN KEY (applied_revision, installation_id)
        REFERENCES operator_config_revision(revision, installation_id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_operator_config_api_ack_status CHECK (
        (status = 'applied'
         AND applied_revision IS NOT NULL
         AND applied_revision = observed_revision
         AND error_code IS NULL)
        OR
        (status = 'rejected'
         AND (applied_revision IS NULL OR applied_revision < observed_revision)
         AND error_code IS NOT NULL
         AND error_code ~ '^[a-z0-9_]{1,64}$')
    )
);

CREATE TRIGGER trg_operator_config_api_ack_guard
BEFORE UPDATE OR DELETE ON operator_config_api_ack
FOR EACH ROW EXECUTE FUNCTION guard_operator_config_ack();

CREATE TABLE operator_config_worker_ack (
    singleton SMALLINT PRIMARY KEY CHECK (singleton = 1),
    installation_id UUID NOT NULL,
    observed_revision BIGINT NOT NULL,
    applied_revision BIGINT,
    status VARCHAR(16) NOT NULL CHECK (status IN ('applied', 'rejected')),
    error_code VARCHAR(64),
    observed_at BIGINT NOT NULL,
    CONSTRAINT fk_operator_config_worker_ack_observed
        FOREIGN KEY (observed_revision, installation_id)
        REFERENCES operator_config_revision(revision, installation_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_operator_config_worker_ack_applied
        FOREIGN KEY (applied_revision, installation_id)
        REFERENCES operator_config_revision(revision, installation_id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_operator_config_worker_ack_status CHECK (
        (status = 'applied'
         AND applied_revision IS NOT NULL
         AND applied_revision = observed_revision
         AND error_code IS NULL)
        OR
        (status = 'rejected'
         AND (applied_revision IS NULL OR applied_revision < observed_revision)
         AND error_code IS NOT NULL
         AND error_code ~ '^[a-z0-9_]{1,64}$')
    )
);

CREATE TRIGGER trg_operator_config_worker_ack_guard
BEFORE UPDATE OR DELETE ON operator_config_worker_ack
FOR EACH ROW EXECUTE FUNCTION guard_operator_config_ack();
