-- Append-only operator audit trail: one row per authenticated admin/staff
-- mutation (non-GET/HEAD), recorded by the API guard after the response is
-- produced. Request bodies are deliberately not recorded — admin payloads can
-- carry secrets (SMTP, payment-provider credentials, Telegram tokens).
CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT NOT NULL,
    actor_email TEXT NOT NULL,
    session_id TEXT NOT NULL,
    surface TEXT NOT NULL CHECK (surface IN ('admin', 'staff')),
    method TEXT NOT NULL,
    path TEXT NOT NULL,
    status_code INTEGER NOT NULL,
    client_ip TEXT,
    request_id TEXT,
    created_at BIGINT NOT NULL
);

CREATE INDEX idx_audit_log_created_at ON audit_log(created_at);
CREATE INDEX idx_audit_log_actor_id_created_at ON audit_log(actor_id, created_at);

-- Tamper evidence: the trail is append-only for every database principal the
-- application runs as. Corrections happen by appending, never by editing.
CREATE FUNCTION guard_audit_log()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'audit_log is append-only';
END;
$$;

CREATE TRIGGER trg_audit_log_guard
BEFORE UPDATE OR DELETE ON audit_log
FOR EACH ROW EXECUTE FUNCTION guard_audit_log();
