/// Operator-entered minute durations are bounded to one year. This is long
/// enough for every subscription/rate-limit use while keeping Redis expiry and
/// timestamp arithmetic inside a small, predictable range.
pub const MAX_CONFIG_DURATION_MINUTES: i64 = 365 * 24 * 60;
pub(crate) const DEFAULT_PRIVILEGED_SESSION_TTL_SECONDS: i64 = 30 * 60;
pub(crate) const CONFIGURATION_SOURCE_KEY: &str = "configuration_source";
pub(crate) const FILE_ONLY_CONFIGURATION_SOURCE: &str = "file_only";
pub(crate) const CONFIGURATION_SCOPE_KEY: &str = "configuration_scope";
pub(crate) const BOOT_ONLY_CONFIGURATION_SCOPE: &str = "boot_only";
pub(crate) const OPERATOR_AUTHORITY_MARKER: &str = "_v2board_operator_authority_v1";
pub(crate) const MAX_CONFIG_FILE_BYTES: u64 = 2 * 1024 * 1024;

/// Exact common key set for a long-lived role-owned bootstrap document.  The
/// worker validator additionally requires its four ClickHouse writer keys.
/// Dynamic behavior and integration secrets deliberately live only in the
/// PostgreSQL operator authority and therefore cannot leak back into these
/// files after initial materialization.
pub const BOOT_ONLY_RUNTIME_KEYS_V1: &[&str] = &[
    "configuration_source",
    "configuration_scope",
    "runtime_role",
    "environment",
    "bind_addr",
    "cors_allowed_origins",
    "trusted_proxy_cidrs",
    "http_connect_timeout_seconds",
    "http_request_timeout_seconds",
    "api_request_timeout_seconds",
    "password_kdf_max_parallel",
    "app_key",
    "database_url",
    "peer_database_principal",
    "redis_url",
];

/// Every application-behavior key required by the version-1 file-only runtime
/// document. Database and Redis URLs are supplied by the target configuration and
/// are required in the materialized file in addition to this list.
pub const FILE_ONLY_RUNTIME_KEYS_V1: &[&str] = &[
    "configuration_source",
    "environment",
    "bind_addr",
    "cors_allowed_origins",
    "trusted_proxy_cidrs",
    "http_connect_timeout_seconds",
    "http_request_timeout_seconds",
    "api_request_timeout_seconds",
    "password_kdf_max_parallel",
    "auth_session_ttl_seconds",
    "privileged_auth_session_ttl_seconds",
    "auth_session_max_per_user",
    "privileged_step_up_enable",
    "privileged_step_up_ttl_seconds",
    "privileged_step_up_max_attempts",
    "privileged_step_up_attempt_window_seconds",
    "app_key",
    "app_name",
    "app_url",
    "app_description",
    "logo",
    "tos_url",
    "force_https",
    "email_verify",
    "email_template",
    "email_host",
    "email_port",
    "email_username",
    "email_password",
    "email_encryption",
    "email_from_address",
    "stop_register",
    "invite_force",
    "invite_never_expire",
    "email_whitelist_enable",
    "email_whitelist_suffix",
    "email_gmail_limit_enable",
    "recaptcha_enable",
    "recaptcha_site_key",
    "recaptcha_key",
    "register_limit_by_ip_enable",
    "register_limit_count",
    "register_limit_expire",
    "telegram_bot_enable",
    "telegram_bot_token",
    "telegram_discuss_id",
    "telegram_channel_id",
    "telegram_discuss_link",
    "commission_withdraw_method",
    "withdraw_close_enable",
    "currency",
    "currency_symbol",
    "commission_distribution_enable",
    "commission_auto_check_enable",
    "commission_distribution_l1",
    "commission_distribution_l2",
    "commission_distribution_l3",
    "subscribe_url",
    "subscribe_path",
    "show_subscribe_method",
    "show_subscribe_expire",
    "show_info_to_server_enable",
    "allow_new_period",
    "reset_traffic_method",
    "try_out_enable",
    "try_out_plan_id",
    "try_out_hour",
    "plan_change_enable",
    "surplus_enable",
    "invite_commission",
    "commission_first_time_enable",
    "new_order_event_id",
    "renew_order_event_id",
    "change_order_event_id",
    "deposit_bounus",
    "invite_gen_limit",
    "ticket_status",
    "commission_withdraw_limit",
    "server_token",
    "server_require_idempotency_key",
    "server_api_url",
    "server_push_interval",
    "server_pull_interval",
    "server_node_report_min_traffic",
    "server_device_online_min_traffic",
    "device_limit_mode",
    "server_log_enable",
    "server_v2ray_domain",
    "server_v2ray_protocol",
    "frontend_theme_color",
    "frontend_background_url",
    "frontend_admin_path",
    "secure_path",
    "safe_mode_enable",
    "password_limit_enable",
    "password_limit_count",
    "password_limit_expire",
    "windows_version",
    "windows_download_url",
    "macos_version",
    "macos_download_url",
    "android_version",
    "android_download_url",
];

/// Reserved public top-level path segments (docs/api-dialect.md §10.2). The
/// resolved admin path serves the admin HTML subtree ahead of the user-SPA
/// fallback and builds the dynamic admin API prefix, so it may not shadow a
/// fixed public route root, a user-SPA route root, or a reserved API
/// namespace. The `crc32b_hex` fallback is eight hex characters and can never
/// equal an entry here.
pub(crate) const RESERVED_ADMIN_PATH_SEGMENTS: &[&str] = &[
    // Fixed public routes.
    "api",
    "assets",
    "healthz",
    "readyz",
    "robots.txt",
    // User-SPA route roots.
    "login",
    "register",
    "forgetpassword",
    "dashboard",
    "plan",
    "order",
    "profile",
    "node",
    "traffic",
    "invite",
    "ticket",
    "knowledge",
    // API namespaces.
    "auth",
    "user",
    "public",
    "staff",
    "client",
    "server",
    "guest",
    "passport",
];

/// Application behavior owned by the versioned operator-configuration
/// authority.  Bootstrap-only credentials and process topology (database,
/// Redis, ClickHouse, listener, paths, environment, and `app_key`) are
/// deliberately absent: changing those values requires a coordinated restart.
///
/// Keep this list in lockstep with [`AppConfig::operator_config_map`].  A
/// snapshot read from PostgreSQL is rejected if it contains a key outside this
/// set, preventing a database row from becoming an undocumented override for a
/// boot-bound setting.
pub const OPERATOR_CONFIG_KEYS_V1: &[&str] = &[
    "auth_session_ttl_seconds",
    "privileged_auth_session_ttl_seconds",
    "auth_session_max_per_user",
    "privileged_step_up_enable",
    "privileged_step_up_ttl_seconds",
    "privileged_step_up_max_attempts",
    "privileged_step_up_attempt_window_seconds",
    "app_name",
    "app_url",
    "app_description",
    "logo",
    "tos_url",
    "force_https",
    "email_verify",
    "email_template",
    "email_host",
    "email_port",
    "email_username",
    "email_password",
    "email_encryption",
    "email_from_address",
    "stop_register",
    "invite_force",
    "invite_never_expire",
    "email_whitelist_enable",
    "email_whitelist_suffix",
    "email_gmail_limit_enable",
    "recaptcha_enable",
    "recaptcha_site_key",
    "recaptcha_key",
    "register_limit_by_ip_enable",
    "register_limit_count",
    "register_limit_expire",
    "telegram_bot_enable",
    "telegram_bot_token",
    "telegram_discuss_id",
    "telegram_channel_id",
    "telegram_discuss_link",
    "commission_withdraw_method",
    "withdraw_close_enable",
    "currency",
    "currency_symbol",
    "commission_distribution_enable",
    "commission_auto_check_enable",
    "commission_distribution_l1",
    "commission_distribution_l2",
    "commission_distribution_l3",
    "subscribe_url",
    "subscribe_path",
    "show_subscribe_method",
    "show_subscribe_expire",
    "show_info_to_server_enable",
    "allow_new_period",
    "reset_traffic_method",
    "try_out_enable",
    "try_out_plan_id",
    "try_out_hour",
    "plan_change_enable",
    "surplus_enable",
    "invite_commission",
    "commission_first_time_enable",
    "new_order_event_id",
    "renew_order_event_id",
    "change_order_event_id",
    "deposit_bounus",
    "invite_gen_limit",
    "ticket_status",
    "commission_withdraw_limit",
    "server_token",
    "server_require_idempotency_key",
    "server_api_url",
    "server_push_interval",
    "server_pull_interval",
    "server_node_report_min_traffic",
    "server_device_online_min_traffic",
    "device_limit_mode",
    "server_log_enable",
    "server_v2ray_domain",
    "server_v2ray_protocol",
    "frontend_theme_color",
    "frontend_background_url",
    "frontend_admin_path",
    "secure_path",
    "legacy_hash_redirect_enable",
    "safe_mode_enable",
    "admin_mfa_force",
    "password_limit_enable",
    "password_limit_count",
    "password_limit_expire",
    "windows_version",
    "windows_download_url",
    "macos_version",
    "macos_download_url",
    "android_version",
    "android_download_url",
];
